####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                      A practical, secure and friendly authentication plugin                  | #
# |                                                                                              | #
# |                                © 2026 - Powered by nickuc.com                                | #
# |                                                                                              | #
# |                                                                                              | #
# |  Для лучшего понимания этого файла смотрите нашу документацию:                               | #
# |   ==> https://docs.nickuc.com/nlogin/                                                        | #
# |                                                                                              | #
# |  Сообщество в VK:                                                                            | #
# |   ==> https://www.nickuc.com/vk                                                              | #
# |                                                                                              | #
# |  Новые опции не добавляются автоматически в этот файл. Если опция не найдена,                | #
# |  используются значения по умолчанию.                                                         | #
# |                                                                                              | #
# |  Russian translation made by Vadimus 2.0#8694 <3                                             | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Установите версию файла.
language-version: 5

# Установите язык плагина
#
# - Доступные переводы:
#
# |=> Арабский: messages_ar.yml
# |=> Болгария: messages_bg.yml
# |=> Китайский: messages_cn.yml
# |=> Чешский: messages_cz.yml
# |=> немецкий: messages_de.yml
# |=> Английский: messages_en.yml
# |=> Испанский: messages_es.yml
# |=> французский: messages_fr.yml
# |=> Венгерский: messages_hu.yml
# |=> Индонезийский: messages_id.yml
# |=> Итальянский: messages_it.yml
# |=> Японский: messages_jp.yml
# |=> Литовский: messages_lt.yml
# |=> Польский: messages_pl.yml
# |=> Португальский: messages_br.yml
# |=> Румынский: messages_ro.yml
# |=> Русский: messages_ru.yml    <--- (нынешний язык)
# |=> турецкий: messages_tr.yml
# |=> Украинский: messages_ua.yml
# |=> вьетнамский: messages_vn.yml
#
# - При смене языка текущий файл НЕ будет сброшен.
language-file: "messages_ru.yml"

#      ___      _      _____      _
#     /   \    /_\    /__   \    /_\
#    / /\ /   //_\\     / /\/   //_\\
#   / /_//   /  _  \   / /     /  _  \
#  /___,'    \_/ \_/   \/      \_/ \_/

# Настройки баз данных.
database:
  # Устанавливает тип используемой базы данных.
  #
  # - Доступные опции:
  #  |=> MariaDB
  #  |=> MySQL
  #  |=> SQLite
  type: SQLite

  remote:
    # Определяет информацию о MariaDB/MySQL.
    # - Учебник по установке: https://docs.nickuc.com/nlogin/mysql
    hostname: "localhost:3306"
    database: "nLogin"
    username: "root"
    password: ""

    # Установите свойства соединения.
    # - Не изменяйте эту информацию, если вы не знаете, что делаете!
    properties:
      #useSSL: false
      #sslMode: disable
      #verifyServerCertificate: true
      useUnicode: true
      characterEncoding: "utf8"

  # Определяет параметры пула соединений.
  # - Не изменяйте эту информацию, если вы не знаете, что делаете!
  pool-settings:
    maximum-pool-size: 10
    minimum-idle: 10
    maximum-lifetime: 1800000 # 30 минут
    connection-timeout: 5000 # 5 секунд

  table:
    account:
      # Задает имя таблицы учетных записей nLogin.
      # - Не изменяйте эту информацию, если вы не знаете, что делаете!
      table-name: "nlogin"

      # Задает имя столбцов nLogin.
      # - Не изменяйте эту информацию, если не знаете, что делаете!
      columns:
        ai: "ai"
        last-name: "last_name"
        unique-id: "unique_id"
        mojang-id: "mojang_id"
        bedrock-id: "bedrock_id"
        password: "password"
        premium: "premium"
        last-ip: "last_ip"
        last-seen: "last_seen"
        creation-date: "creation_date"
        email: "email"
        discord: "discord"
        settings: "settings"

    data:
      # Задает имя таблицы данных nLogin.
      # - Не изменяйте эту информацию, если вы не знаете, что делаете!
      table-name: "nlogin_data"

      # Задает имя столбцов nLogin.
      # - Не изменяйте эту информацию, если не знаете, что делаете!
      columns:
        id: "id"
        key: "key"
        value: "value"

# Настройки службы обмена сообщениями
redis:
  # Определяет информацию о Redis.
  enable: false
  hostname: localhost
  username: ""
  password: ""
  ssl: false

#     __      _____                ___      ___
#    / /      \_   \    /\/\      / __\    /___\
#   / /        / /\/   /    \    /__\//   //  //
#  / /___   /\/ /_    / /\/\ \  / \/  \  / \_//
#  \____/   \____/    \/    \/  \_____/  \___/

# Настройки Limbo.
# - Limbo - это система защиты информации игрока.
# - В случае внезапного отключения (например, отключения питания)
# в действие вступят файлы limbo.
limbo:
  # Устанавливает время ожидания скрытия информации об игроке.
  #
  # => Указанное значение должно быть в тиках. Чтобы вычислить необходимое количество тиков,
  #    умножьте значение (в секундах) на 20.
  #
  #    - Пример:
  #     2 секунды X 20 тиков = 40 тиков.
  #
  delay: 0

  # Определяет, должен ли лимбо скрывать информацию игроков.
  #
  # => Список информации об игроке:
  #   - скорость и режим полета;
  #   - скорость при ходьбе;
  #   - жизнь;
  #   - сытость;
  #   - [...]
  #
  # - Рекомендуется отключить эту опцию в случае конфликтов с другими
  #   плагинами, которые работают с этими параметрами (например, плагинами лобби).
  hide-player-stats: true

  # Устанавливает, должны ли предметы быть скрыты перед входом в систему.
  hide-player-inventory: true

  # Устанавливает, следует ли скрывать других игроков перед входом в игру.
  # - Эта опция может предотвратить спам ботов в списке игроков сервера.
  hide-unauthenticated-players: true

  # Определяет, следует ли блокировать движение перед авторизацией.
  block-player-movement: true

  # Определяет, будет ли эффект ослепления добавляться перед входом в систему.
  use-blindness-effect: false

  # Устанавливает, будет ли игрок телепортирован в безопасное место при входе.
  # - Рекомендуется активировать опцию, если не задан спаун.
  highest-block-location: false

  unrestricted:
    # Определяет псевдонимы, которые будут пропускать процесс аутентификации.
    #
    # - Эта опция может быть полезна для МОДов или плагинов, которые подменяют
    #   поведение игрока.
    #
    # - Примеры:
    #  - '[ThaumcraftTablet]''
    #  - '[BuildCraft]'
    #  - 'ComputerCraft'
    #
    # => Используйте эту функцию на свой страх и риск.
    nicknames:
    #- '[ThaumcraftTablet]'
    #- '[BuildCraft]'
    #- 'ComputerCraft'

    # Задает имена инвентарей, которые не будут блокироваться перед входом в систему.
    # - Если вы разработчик, то лучше использовать более высокий приоритет для
    #   вашего события инвентаризации (например, HIGH или HIGHEST), а затем удалить
    #   отмену nLogin - "Event#setCancelled(false)"
    inventories:
    #- 'My Inventory Name'

#   __         __      ___               __      _____    _____
#  / _\       /__\    / __\   /\ /\     /__\     \_   \  /__   \  /\_/\
#  \ \       /_\     / /     / / \ \   / \//      / /\/    / /\/  \_ _/
#  _\ \     //__    / /___   \ \_/ /  / _  \   /\/ /_     / /      / \
#  \__/     \__/    \____/    \___/   \/ \_/   \____/     \/       \_/

# Общие настройки безопасности.
security:
  # Устанавливает время аутентификации игрока (в секундах).
  auth-timeout: 90

  # Устанавливает, будут ли команды nLogin с высокой степенью риска отключены в игре.
  # - Эта опция может предотвратить хакерские атаки, удаляющие регистрацию администратора.
  force-console-usage: true

  nickname:
    # Устанавливает regex для проверки ников.
    validation-regex: '([a-zA-Z0-9_]{3,16})'

    kick-unregistered:
      # Определяет, следует ли блокировать незарегистрированных игроков.
      enable: false

      bypass:
        # Определяет, следует ли игнорировать премиум-игроков при применении ограничения.
        premium: false

        # Определяет, следует ли игнорировать игроков Bedrock при применении ограничения.
        bedrock: false

        # Определяет список IP-адресов, которые будут игнорироваться при применении ограничения.
        ips: []

  ip:
    # Устанавливает, должен ли плагин игнорировать проверку "Этот игрок уже онлайн", если IP совпадает с зарегистрированным.
    # - Эта функция полезна, если игрок теряет связь с сервером и пытается войти в систему снова.
    bypass-online-check-with-same-ip: true

    limit:
      # Устанавливает, следует ли использовать ограничитель учетных записей для каждого IP-адреса.
      # - Этот параметр может предотвратить появление поддельных учетных записей.
      enable: true

      # Устанавливает максимальное количество записей на один IP-адрес.
      max: 3

      # Определяет, должен ли IP-ограничитель блокировать доступ учетных записей к серверу.
      prevent-login: false

      bypass:
        # Определяет, должны ли зарегистрированные игроки игнорироваться IP-лимитом.
        registered: true

        # Определяет, должны ли премиум-игроки игнорировать IP-лимит.
        premium: true

        # Определяет, должны ли игроки bedrock игнорировать IP-лимит.
        bedrock: true

        # Определяет список IP-адресов, которые игнорируют ограничение.
        ips:
          - '127.0.0.1'
          - 'localhost'

  passwords:
    # Устанавливает минимальный размер пароля.
    small: 5

    # Устанавливает максимальный размер пароля.
    large: 32

    secure:
      # Определяет, должна ли выполняться проверка надежности пароля.
      enable: false

      # Определяет, должны ли зарегистрированные игроки обновлять свои пароли, если их пароли не соответствуют шаблону безопасного пароля.
      enforce: false

      # Определяет шаблон, используемый для классификации пароля как безопасного.
      #
      #  | По умолчанию проверяется, соответствует ли пароль:
      #- |=> 1. Содержит число
      #- |=> 2. Содержит прописной английский символ
      #- |=> 3. Содержит строчный английский символ
      #- |=> 4. Содержит специальный символ (!"@#$%^&*?)
      #
      secure-regex: '(?=\S*\d)(?=\S*[A-Z])(?=\S*[a-z])(?=\S*[!@#$%^&*?])\S*$'

  bruteforce:
    # Устанавливает максимальное количество неправильных попыток, которые может сделать игрок.
    # - При использовании значения "1" игрок будет немедленно отключен при совершении ошибки.
    max-auth-tries: 1

    punish:
      # Определяет, будут ли атаки грубой силы наказываться автоматически.
      # - После слишком большого количества неправильных попыток подозрительный IP-адрес будет заблокирован.
      enable: true

      # Устанавливает время наказания за предполагаемую атаку грубой силы (в минутах).
      duration: 15

  hashing:
    # Определяет используемый алгоритм хэширования.
    #
    # - Доступные опции:
    #
    #  | Вычислительные затраты хэширования должны увеличиваться (но не обязательно) снизу вверх.
    #  |=> MD5
    #  |=> SHA256
    #  |=> SHA512
    #  |=> BCRYPT2Y
    #  |=> BCRYPT2A
    #  |=> PBKDF2
    #  |=> ARGON2ID
    #  |=> ARGON2I
    #  |=> ARGON2D
    #
    algorithm: "BCRYPT2A"

    bcrypt:
      rounds: 10

    pbkdf2:
      iterations: 10000
      algorithm: "HmacSHA512"

    argon2:
      iterations: 5
      memory: 32
      parallelism: 1

#             _____
#   /\ /\     \_   \
#  / / \ \     / /\/
#  \ \_/ /  /\/ /_
#   \___/   \____/

# Настройки пользовательского интерфейса.
ui:
  # Определяет режим работы диалоговых окон.
  # - Эта функция работает только в версиях 1.21.6 и выше.
  #
  # - Доступные опции:
  #  |=> NONE: отключает диалоговые окна.
  #  |=> PRE_LOGIN: отправляет перед входом на сервер.
  #  |=> AFTER_LOGIN: отправляет после входа на сервер.
  #
  show-dialogs: PRE_LOGIN

  # Устанавливает, будут ли отправляться экранные сообщения.
  use-title-bar: true

  # Устанавливает, будут ли отправляться сообщения на панелях действий.
  use-action-bar: true

  # Устанавливает, будет ли отправляться сообщение об оставшемся времени.
  use-action-bar-timer: true

  # Устанавливает, будут ли отправляться звуковые эффекты.
  use-sounds: true

  # Определяет, будут ли сообщения чата отключены до завершения аутентификации.
  remove-chat-messages: true

  # Устанавливает, будет ли удаляться входное сообщение.
  remove-join-message: false

  # Определите, должен ли язык nLogin быть адаптирован к языку Minecraft.
  language-by-client: false

#     ___      ___                          _          __       ___    __
#    / __\    /___\    /\/\      /\/\      /_\      /\ \ \     /   \  / _\
#   / /      //  //   /    \    /    \    //_\\    /  \/ /    / /\ /  \ \
#  / /___   / \_//   / /\/\ \  / /\/\ \  /  _  \  / /\  /    / /_//   _\ \
#  \____/   \___/    \/    \/  \/    \/  \_/ \_/  \_\ \/    /___,'    \__/

# Параметры команды.
commands:
  # Определяет список команд, которые будут выполняться после регистрации.
  #
  # - Доступные опции:
  #  |=> @console: выполняет команду на консоли.
  #  |=> @delay <время в тиках>: добавляет задержку к команде.
  #  |=> @proxy: выполняет команду на прокси-сервере (только если вы его используете).
  #  |=> @server <серверы, разделенные на ",">: выполняет команду, только если игрок подключен к
  #      списку определенных серверов (только при использовании прокси-сервера).
  #
  #      Пример: @server lobby1,lobby2.
  #
  after-register:
  #- "@console tell @player Welcome to the server!" # запустить в консоли
  #- "@delay 40 /kit starter" # подождать 40 тиков (2с)

  # Определяет список команд, которые будут выполняться после аутентификации.
  #
  # - Доступные опции:
  #  |=> @console: выполняет команду на консоли.
  #  |=> @delay <время в тиках>: добавляет задержку к команде.
  #  |=> @proxy: выполняет команду на прокси-сервере (только если вы его используете).
  #  |=> @server <серверы, разделенные на ",">: выполняет команду, только если игрок подключен к
  #      списку определенных серверов (только при использовании прокси-сервера).
  #
  #      Пример: @server lobby1,lobby2.
  #
  after-login:
  #- "@console @proxy send @player lobby" # запустить в консоли прокси (тарзанка, скорость и т.д.)

  # Определите список разрешенных команд перед авторизацией.
  allowed-commands:
  #- "/loginstaff"

  changepass:
    enable: true
    commands: [changepass, changepassword]
    description: Команда изменения зарегистрированного пароля.
    permission: null
  discord:
    enable: true
    commands: [discord]
    description: Команда для управления 2FA с помощью учетных записей Discord.
    permission: nlogin.command.discord
  email:
    enable: true
    commands: [email]
    description: Команда для управления 2FA с помощью учетных записей электронной почты.
    permission: nlogin.command.email
  login:
    enable: true
    commands: [login, l, log]
    description: Команда для входа на сервер.
    permission: null
  offline:
    enable: true
    commands: [offline, cracked]
    description: Команда для пометки учетной записи как автономной.
    permission: null
  premium:
    enable: true
    commands: [premium]
    description: Команда для пометки учетной записи как премиум.
    permission: null
  recover:
    enable: true
    commands: [recover]
    description: Команда восстановления доступа к зарегистрированным счетам.
    permission: null
  register:
    enable: true
    commands: [register, reg]
    description: Команда для регистрации на сервере.
    permission: null
  unregister:
    enable: false
    commands: [unregister]
    description: Команда для отмены регистрации.
    permission: null