####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                      A practical, secure and friendly authentication plugin                  | #
# |                                                                                              | #
# |                                © 2026 - Powered by nickuc.com                                | #
# |                                                                                              | #
# |                                                                                              | #
# |  Для лучшего понимания этого файла смотрите нашу документацию:                               | #
# |   ==> https://docs.nickuc.com/nlogin/                                                        | #
# |                                                                                              | #
# |  Сообщество в VK:                                                                            | #
# |   ==> https://www.nickuc.com/vk                                                              | #
# |                                                                                              | #
# |  Новые опции не добавляются автоматически в этот файл. Если опция не найдена,                | #
# |  используются значения по умолчанию.                                                         | #
# |                                                                                              | #
# |  Russian translation made by Vadimus 2.0#8694 <3                                             | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Установите версию файла.
language-version: 5

# Определяет, что делать, когда обнаруживаются игроки с премиум-никнеймами.
#
#  (!) Эта опция доступна только в том случае, если опция "username-appender" отключена.
#
# - Доступные опции:
#  |=> DETECT
#    - При выборе этого варианта игроки будут автоматически зарегистрированы как премиум-пользователи.
#
#    (!) Игроки, находящиеся в оффлайне и использующие ник премиум-аккаунта, при
#        первом входе на сервер получат не настраиваемое сообщение "Invalid session".
#
#  |=> RESTRICT
#    - При выборе этого параметра игроки будут автоматически зарегистрированы как премиум-игроки, но офлайн-игроки не смогут использовать премиум-никнейм.
#
#  |=> NONE
#    - При выборе этого параметра никаких действий не будет предпринято.
#
premium-nickname: DETECT

# Определяет, что делать, когда обнаруживаются игроки с премиум-UUID.
#
#  (!) Эта опция работает только для более поздних версий (1.19.1+)
#
# - Доступные опции:
#  |=> DETECT
#    - При выборе этого варианта игроки будут автоматически зарегистрированы как премиум-пользователи.
#
#  |=> RESTRICT
#    - При выборе этого параметра игроки будут автоматически зарегистрированы как премиум-игроки, но офлайн-игроки не смогут использовать премиум-UUID.
#
#  |=> NONE
#    - При выборе этого параметра никаких действий не будет предпринято.
#
premium-id: DETECT

# Устанавливает, должны ли игроки получать уведомление, спрашивающее, являются ли их учетные записи премиум-аккаунтами.
# - Этот параметр рекомендуется использовать, если вы хотите, чтобы премиум-игроки получали UUID Mojang.
premium-question: true

#     _        ___      ___      __        __       ___      __      __
#    /_\      / _ \    / _ \    /__\    /\ \ \     /   \    /__\    /__\
#   //_\\    / /_)/   / /_)/   /_\     /  \/ /    / /\ /   /_\     / \//
#  /  _  \  / ___/   / ___/   //__    / /\  /    / /_//   //__    / _  \
#  \_/ \_/  \/       \/       \__/    \_\ \/    /___,'    \__/    \/ \_/

username-appender:
  # Устанавливает, должен ли плагин добавлять расширение к псевдониму.
  # - Эта функция рекомендуется для того, чтобы отличать премиум-игроков от оффлайн-игроков.
  #
  # - Вы можете свободно изменить этот параметр: данные игроков не будут потеряны.
  #
  # - Для получения более подробной информации обратитесь к документации:
  #    * https://docs.nickuc.com/nlogin/username-appender
  #
  enable: true

  premium:
    # Устанавливает префикс/суффикс, добавляемый к никнеймам премиум-игроков.
    username-appendix: ""

    # Устанавливает положение приложения, добавляемого к никнеймам премиум-игроков.
    #
    # - Имеются опции:
    #  |=> PREFIX (до псевдонима)
    #  |=> SUFFIX (после псевдонима)
    #
    position: "suffix"

    # Определяет список доменов, которые будут использоваться для идентификации премиум-игроков.
    # - Принимаются регекс-выражения.
    # - Проверяемые домены всегда будут в нижнем регистре.
    domains:
    #- "premium.myserver.com"

  offline:
    # Устанавливает префикс/суффикс, добавляемый к никнеймам оффлайн-игроков.
    username-appendix: "+"

    # Устанавливает положение приложения, добавляемого к никнеймам оффлайн-игроков.
    #
    # - Имеются опции:
    #  |=> PREFIX (до псевдонима)
    #  |=> SUFFIX (после псевдонима)
    #
    position: "suffix"

    # Определяет список доменов, которые будут использоваться для идентификации автономных игроков.
    # - Принимаются регекс-выражения.
    # - Проверяемые домены всегда будут в нижнем регистре.
    domains:
    #- "myserver.com"

#     _               _____      ___      __      ___      ___     _____        __
#    /_\     /\ /\   /__   \    /___\    / /     /___\    / _ \    \_   \    /\ \ \
#   //_\\   / / \ \    / /\/   //  //   / /     //  //   / /_\/     / /\/   /  \/ /
#  /  _  \  \ \_/ /   / /     / \_//   / /___  / \_//   / /_\\   /\/ /_    / /\  /
#  \_/ \_/   \___/    \/      \___/    \____/  \___/    \____/   \____/    \_\ \/

autologin:
  bedrock:
    # Определяет, должны ли игроки Bedrock автоматически проходить аутентификацию.
    # - Вы можете свободно изменить этот параметр: уже зарегистрированные пользователи
    #   НЕ будут уязвимы при этом изменении
    enable: true

    # Устанавливает, должны ли игроки Bedrock пропускать регистрацию.
    # - Рекомендуется отключить этот параметр, если вы используете пароли игроков
    #   в веб-интеграции (например, на сайте сервера).
    skip-register: true

    # Определяет, будет ли использоваться UUID базы данных вместо UUID, предоставляемого Floodgate.
    use-database-uuid: false

  premium:
    # Определяет, должны ли премиум-игроки автоматически проходить аутентификацию.
    # - Вы можете свободно изменить этот параметр: уже зарегистрированные пользователи
    #   НЕ будут уязвимы при этом изменении.
    enable: true

    # Определяет, смогут ли премиум-игроки входить в систему с помощью зарегистрированного пароля, если серверы будут отключены.
    # - Премиум-пользователи без зарегистрированного пароля смогут зарегистрироваться и
    #   НЕ будут уязвимы в связи с этим изменением.
    allow-if-offline: false

    # Определяет, должны ли премиум-игроки пропускать регистрацию.
    # - Рекомендуется отключить этот параметр, если вы используете пароли игроков
    #   в веб-интеграции (например, на сайте сервера).
    skip-register: true

  session:
    # Определяет, будут ли использоваться сессии входа в систему.
    # - Аутентификация будет игнорироваться, если игрок войдет в игру по тайм-ауту
    #   и продолжит использовать тот же IP-адрес.
    enable: true

    # Устанавливает продолжительность (в минутах) сеансов входа в систему.
    # => Очень длинные сессии могут открыть уязвимости, если IP игрока
    #    является публичным (прокси-серверы, публичные VPN, общие сети)
    #    или если он переключается слишком быстро (на провайдерах с динамическим IP).
    duration: 1

    bypass:
      # Определяет, какие игроки должны игнорироваться при входе в систему.
      nicknames: []

      # Определяет, какие IP-адреса должны игнорироваться при входе в систему.
      ips: []