####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                      A practical, secure and friendly authentication plugin                  | #
# |                                                                                              | #
# |                                © 2026 - Powered by nickuc.com                                | #
# |                                                                                              | #
# |                                                                                              | #
# |  Для лучшего понимания этого файла смотрите нашу документацию:                               | #
# |   ==> https://docs.nickuc.com/nlogin/                                                        | #
# |                                                                                              | #
# |  Сообщество в VK:                                                                            | #
# |   ==> https://www.nickuc.com/vk                                                              | #
# |                                                                                              | #
# |  Новые опции не добавляются автоматически в этот файл. Если опция не найдена,                | #
# |  используются значения по умолчанию.                                                         | #
# |                                                                                              | #
# |  Russian translation made by Vadimus 2.0#8694 <3                                             | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Не трогайте это значение
language-version: 5

# Определяет, может ли электронная почта использоваться в качестве второго фактора.
enable: false

authentication:
  # Электронная почта
  email: "yourserver@domain.com"
  # С сайта
  from: "Ваш сервер"
  # Пользователь
  user: ""
  # Пароль
  password: "123456"

  # Charset
  charset: "UTF-8"
  # Mimetype
  mimetype: "text/html"

  # SMTP-хост
  host: "smtp.gmail.com"
  # SMTP-порт
  port: 587

  # Шифрование
  #
  # - Доступные опции:
  #  |=> AUTO
  #  |=> TLS
  #  |=> SSL
  encryption: AUTO

  # Debug mode
  debug: false

linking:
  # Определяет, должна ли данная ссылка быть рекомендована игрокам.
  recommend: true

  # Определяет, будет ли 2FA включена после завершения связывания.
  enable-2fa: true

  required:
    # Устанавливает, будет ли требоваться привязка электронной почты для аутентификации.
    enable: false

    # Устанавливает, нужно ли премиум-игрокам также привязывать электронную почту для аутентификации.
    enable-for-premium: true

    # Устанавливает, нужно ли игрокам Bedrock также привязывать адрес электронной почты для аутентификации.
    enable-for-bedrock: true

account:
  # Устанавливает максимальное количество учетных записей, к которым может быть привязана одна и та же электронная почта.
  limit: 1

  # Определяет, следует ли создавать новый пароль после процесса восстановления учетной записи.
  # - Если этот параметр отключен, будет установлен случайный пароль.
  force-password-update: false

  # Определяет список разрешенных доменов.
  # - Если домен не задан, то будут разрешены все домены.
  allowed-domains: []

  # Определяет список запрещенных доменов.
  denied-domains: []