####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                      A practical, secure and friendly authentication plugin                  | #
# |                                                                                              | #
# |                                © 2026 - Powered by nickuc.com                                | #
# |                                                                                              | #
# |                                                                                              | #
# |  Для лучшего понимания этого файла смотрите нашу документацию:                               | #
# |   ==> https://docs.nickuc.com/nlogin/                                                        | #
# |                                                                                              | #
# |  Сообщество в VK:                                                                            | #
# |   ==> https://www.nickuc.com/vk                                                              | #
# |                                                                                              | #
# |  Новые опции не добавляются автоматически в этот файл. Если опция не найдена,                | #
# |  используются значения по умолчанию.                                                         | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Не трогайте это значение
language-version: 5

# Определяет, можно ли использовать Discord в качестве второго фактора.
enable: false

authentication:
  # Определяет токен, используемый в Discord API.
  #
  # - Для получения более подробной информации обратитесь к документации:
  #    * https://docs.nickuc.com/nlogin/discord
  #
  token: ""

  # Устанавливает сообщение о состоянии бота.
  presence: ""

  proxy:
    enable: false
    host: "https://domain.tld"
    port: 80
    username: "username"
    password: "password"

linking:
  # Устанавливает URL-адрес приглашения на сервер Discord.
  # - Эта опция необходима для завершения ссылки.
  invite-url: "https://discord.gg/YOUR_INVITE_CODE"

  # Определяет, должна ли данная ссылка быть рекомендована игрокам.
  recommend: true

  # Определяет, будет ли 2FA включена после завершения связывания.
  enable-2fa: true

  required:
    # Устанавливает, будет ли требоваться привязка учетной записи Discord для аутентификации.
    enable: false

    # Устанавливает, нужно ли премиум-игрокам также привязывать учетную запись Discord для аутентификации.
    enable-for-premium: true

    # Устанавливает, нужно ли игрокам Bedrock также привязывать учетную запись Discord для аутентификации.
    enable-for-bedrock: true

account:
  # Устанавливает максимальное количество учетных записей, которые могут иметь одну и ту же связь с Discord.
  limit: 1

  # Определяет, сколько времени (в секундах) должна быть ранее создана учетная запись, чтобы получить разрешение на привязку.
  # - Значение по умолчанию - 5 минут (600 секунд).
  # - Чтобы отключить время проверки регистрации учетной записи, измените значение на "-1".
  block-recent: 600

  # Определяет, следует ли создавать новый пароль после процесса восстановления учетной записи.
  # - Если этот параметр отключен, будет установлен случайный пароль.
  force-password-update: false