####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                                  一款实用、安全、友好的身份验证插件                                | #
# |                                                                                              | #
# |                                © 2026 - 由 nickuc.com 提供支持                                 | #
# |                                                                                              | #
# |                                                                                              | #
# |  为了更好地理解这个文件,请参阅我们的文档:                                                           | #
# |   ==> https://docs.nickuc.com/nlogin/                                                        | #
# |                                                                                              | #
# |  新选项不会自动添加到此文件中. 如果找不到                                                           | #
# |  选项则使用默认值.                                                                              | #
# |                                                                                              | #
# |  译者:                                                                                        | #
# |   - jhqwqmc                                                                                  | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# 配置文件的版本
language-version: 11

# 设置 Discord 是否可以用作双因素认证 (国内就别想了小心进橘子喝茶)
enable: false

authentication:
  # 设置 Discord API 中使用的令牌
  #
  # - 如需更多信息,请访问文档:
  #    * https://docs.nickuc.com/nlogin/discord
  #
  token: ""

  # 设置机器人状态消息
  presence: ""

  proxy:
    enable: false
    host: "https://domain.tld"
    port: 80
    username: "username"
    password: "password"

linking:
  # 设置 Discord 服务器的邀请URL
  # - 需要此选项才能完成链接
  invite-url: "https://discord.gg/YOUR_INVITE_CODE"

  # 设置是否应将链接推荐给玩家
  recommend: true

  # 定义完成链接后是否启用 2FA
  enable-2fa: true

  required:
    # 设置是否需要链接 Discord 帐户才能进行身份验证
    enable: false

    # 设置正版玩家是否还需要链接 Discord 帐户进行身份验证
    enable-for-premium: true

    # 设置基岩版玩家是否需要关联 Discord 账号进行身份验证
    enable-for-bedrock: true

account:
  # 设置可以链接相同 Discord 的最大帐户数
  limit: 1

  # 定义一个账户需要创建多少时间（秒）才能被批准链接。
  # - 默认值为 5 分钟（600 秒）
  # - 要禁用账户注册验证时间，请将值改为"-1"。
  block-recent: 600

  # 定义是否应在帐户恢复过程之后创建新密码。
  # - 如果禁用此选项，将设置随机密码
  force-password-update: false