####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                      A practical, secure and friendly authentication plugin                  | #
# |                                                                                              | #
# |                                © 2026 - Powered by nickuc.com                                | #
# |                                                                                              | #
# |              List of translation authors: https://crowdin.com/project/nlogin/members         | #
# |                                                                                              | #
# |  New options are not automatically added in this file. Default values are used               | #
# |  if an option is not found.                                                                  | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

pending:
  login: '&fИспользование: &7/&6login <пароль>'
  register: '&fИспользование: &7/&6register <пароль> <повтор пароля>'
  action-bar:
    singular: '&cУ вас есть {0} &fсекунда {для входа///на регистрацию}.'
    plural: '&cУ вас есть {0} &fсекунд(ы) на {вход///регистрацию}.'

success:
  login: '&fВы &aуспешно &Fвошли в аккаунт.'
  register: '&fВы &6успешно &fзарегистрировались.'
  session: '&fСессия активна.'
  premium: '&fВы автоматически зашли, так как используете &6лицензию&f.'
  bedrock: '&fВы автоматически входите в систему, поскольку осуществляете вход из учетной записи &6Bedrock&f.'
  change-password: '&fВаш пароль был &aуспешно &fизменён.'
  reload: '&fПлагин &aуспешно&f перезагружен.'
  kick:
    unregister: '&fРегистрация аккаунта &aуспешно &fотозвана.'
    marked-offline: '&7Ваш аккаунт был помечен как &6пиратский&7, пожалуйста, перезайдите.'
    challenge-premium: '&7Чтобы подтвердить, что вы используете &6лицензию&7, пожалуйста, войдите на сервер еще раз.'

error:
  not-registered: '&fЭтот ник ещё &cне зарегистрирован&f.'
  offline: '&fИгрок сейчас &cне в сети&f.'
  address-limit: '&fВы &cисчерпали &fлимит регистрации аккаунтов.'
  database: '&cИзвините, но эта операция с базой данных не может быть завершена. Пожалуйста, проверьте подробности в консоли.'
  command:
    usage: '&fИспользуйте &6{0}.'
    no-permission: '&fУ вас &cнет прав&f для использования этой команды.'
    player-required: '&fЭту команду &cнельзя &fиспользовать в консоли.'
    console-required: '&fЭту команду &6можно&f использовать &cтолько &fиз консоли.'
    account-collision:
    - '&fБолее одного аккаунта имеет псевдоним &{0}&f:'
    - '&8⋆ &7{1} {2}'
    - ''
    - '&c!! &eЗапустите команду снова, чтобы убедиться, что используется никнейм, соответствующий требуемому типу аккаунта.'
    arguments:
      password: пароль
      current-password: текущий пароль
      new-password: новый пароль
  already:
    login: '&fВы &cуже&f вошли в аккаунт.'
    login-other: '&fЭтот игрок &cуже &fвошёл в аккаунт.'
    registered: '&fЭто имя пользователя &cуже &fзарегистрировано.'
    premium: '&fВаш аккаунт уже отмечен как &6лицензионый.'
  password:
    same-as-current: '&fВведённый пароль должен отличаться от предыдущего.'
    too-large: '&fВы ввели &cслишком &fдлинный пароль.'
    too-small: '&fВы ввели &cслишком &fкороткий пароль.'
    not-secure: '&cУказанный пароль не соответствует требованиям безопасности. Пожалуйста, введите цифру, заглавные и строчные буквы и специальный символ.'
    do-not-match: '&fПароли &cне совпадают&f.'
    require-confirmation: '&fВы должны &6подтвердить &fсвой пароль.'
    incorrect: '&cНеправильный &fпароль! Попробуйте снова.'
  kick:
    incorrect-password: '&fВы слишком много раз ввели &cнеправильный &fпароль.'
    wait-server-start: |-
      &fСервер в процессе запуска.
      &fПодождите его полной загрузки.
    account-blocked: |-
      &fВаш IP-вдрес подозревается в &cатаке &fи был &cзаблокирован&f.&r
      &r&fОставшееся время до разблокировки: &e{0}
    account-unregistered: |-
      &cЭтот сервер не принимает регистрацию новых учетных записей.

      &cДля подробностей, пожалуйста, обратитесь к администрации сервера.
    invalid-nickname: '&fВаш никнейм содержит недопустимые символы. Примеры недопустимых символов:&e<|}-+#$@.'
    bedrock-nickname: '&cВыбранный никнейм &f("{0}") &cограничен для игроков Bedrock.'
    bedrock-unlinked: |-
      &cЭтот никнейм &f("{0}") &cсовпадает с уже существующим никнеймом Java игрока.

      &eЧтобы получить доступ к этой учетной записи, привяжите учётную запись Java к учетной записи Bedrock с помощью &f/linkaccount &ecommand.
    transferred-nickname: |-
      &cВыбранное имя &f("{0}") &cбыло зарезервировано и перенесено на аккаунт с тем же UUID.

      &eДля входа используйте другой никнейм.
    already-online: '&fЭтот игрок &cуже &fзашёл на сервер.'
    unknown-hostname: |-
      &4[nLogin] Используемое имя хоста &f({0}) &4не определено в конфигурации.
      &r
      &r&cЕсли это действительный IP-адрес, добавьте его в наиболее подходящую категорию в разделе конфигурации &f"premium.username-appender"&c.
      &r
      &r&eДля получения более подробной информации ознакомьтесь с руководством по работе с аппендером имени пользователя:
      &r&bhttps://docs.nickuc.com/nlogin/username-appender
    premium-not-logged: |-
      &7Имя пользователя &6{0} &7привязано к подтверждённой &apremium-учётной записи&7, но срок действия вашей сессии &cexpired&7 истек.

      &eЕсли вы являетесь владельцем этой учётной записи, перезапустите Minecraft и войдите в систему заново.
    premium-challenge: |-
      &eПри последней попытке входа нам не удалось пройти аутентификацию вашей учетной записи.

      &fЕсли вы используете &apremium &fаккаунт, перезапустите Minecraft и войдите в систему заново.

      &fЕсли ваша учетная запись находится в &coffline&f-режиме, пожалуйста, войдите в систему заново, чтобы завершить проверку.
    timeout:
      login: '&fВы слишком &cдолго &fвходили в аккаунт.'
      register: '&fВремя регистрации &cистекло&f.'

notification:
  all-viewed: '&fВсе уведомления были &2просмотрены&f.'
  premium-question:
  - ''
  - ' &eИспользуете ли вы лицензию?'
  - ' &7(&fпосле принятия вам нужно будет переподключиться к серверу&f).'
  - ''
  premium-transfer-question:
  - ''
  - ' &eУже зарегистрирован пиратский аккаунт с ником &f@player&e.'
  - ''
  - ' &6Вы хотите перенести данные из этого аккаунта или создать новую учетную запись?'
  - ''
  - ' &c!! &eВы должны авторизоваться для подтверждения владения аккаунта.'
  - ''
  premium-transfer-confirmation:
  - ''
  - ' &6Хотите ли вы подтвердить передачу данных с &f@player &6на ваш лицензионный аккаунт?'
  - ''
  - ' &c!! После подтверждения передачи, вам надо нужно перезайти на сервер.'
  - ''
  password-update:
  - ''
  - ' &eВаш пароль необходимо сбросить.'
  - ''
  - ' &7Пожалуйста, измените пароль с помощью следующей команды:'
  - ' &f/changepass <текущий пароль> <новый пароль>'
  - ''
  button:
    confirm-read:
      text: '&a[✔️ Подтвердить прочтение]'
      hover: null
    yes-btn:
      text: '&a[✔ Да]'
      hover: null
    no-btn:
      text: '&c[✖ Нет]'
      hover: null
    new-account:
      text: '&a[Новый Аккаунт]'
      hover: null
    transfer-data:
      text: '&9[Перенос данных]'
      hover: null

2fa:
  not-registered: '&fУ вас &cнет &fаккаунта &6{0}.'
  already-registered: '&fВы &cуже&f зарегистрировали свой &6{0}.'
  register-limit: '&cВы исчерпали лимит учетных записей с одинаковыми {0}.'
  unregistered: '&eВаш {0} был успешно отвязан.'
  incorrect-code: '&fВы ввели &cневерный &fпароль. Попробуйте снова.'
  rate-limit: '&cЛимит превышен. Пожалуйста, подождите {0} минут, чтобы попробовать снова.'
  confirmed-account: '&aВаш {0} аккаунт был успешно зарегистрирован.'
  confirmation-message-sent: |-
    &fКод подтверждения был отправлен на ваш &6&6{0}&7.
    &8(&f{1}&8).
  command-delay: '&fПодождите некоторое время, прежде чем снова выполнять эту команду.'
  help-command:
  - ''
  - ' &fСтатус: [&6{2} подключен//&c{2} не подключен]&f.'
  - ''
  - ' [&8⋆ &7/&6{0} add &7- &fПривязать {1}]'
  - ' [&8⋆ &7/&6{0} remove &7- &fОтвязать {1}]'
  - ' [&8⋆ &7/&6{0} recover &7- &fВосстановить аккаунт]'
  - ' [&8⋆ &7/&6{0} 2fa &7- &fВключить/Отключить 2FA]'
  - ''
  recover-command:
  - ''
  - ' &eВыберите метод восстановления:'
  - ' [&8⋆ &7{0}: &f/{1} recover]'
  - ''
  switch:
    enabled: '&f2FA был &2активирован&f.'
    disabled: '&f2FA был &cотключен&f.'
  recover:
    not-equal: '&fДанный &e{0}&f не совпадает с зарегистрированным.'
    message-sent: '&fНа ваш &6привязанный аккаунт&f было отправлено сообщение о восстановлении.'
    change-password: '&fВаш пароль был автоматически изменен на &e''{0}''&f.'
  discord:
    account-linked: |-
      &aПоздравляем, ваш аккаунт успешно привязан.
      &fВы привязались к &6{0}&f.
    confirm-account:
    - ''
    - ' &fДля завершения, вам требуется подтвердить&a Дискорд-аккаунт&f.'
    - ' &7Присоединитесь к &b{0} &7и напишите'
    - ' &7напишите нашему боту: &e{1}'
    - ''
    - ' [&2Нажмите сюда&f, чтобы получить команду.]'
    - ''
    warn-message:
    - ''
    - ' &6Система безопасности Discord'
    - ' &7Ваш &9Discord&7. Выполняя это, Вы'
    - ' &fС привязкой к &aDiscord&f, вы максимально защитите свой аккаунт.'
    - ''
    discord-required:
    - ''
    - ' &7Текущий сервер требует, чтобы вы привязали'
    - ' &aDiscord аккаунт &7для завершения регистрации.'
    - ''
    - ' &6Пожалуйста, выполните &f/discord add&6.'
    - ''
    address-changed:
    - ''
    - ' &7Вам нужно подтвердить вход в аккаунт.'
    - ' &7Сообщение безопасности было отправлено на ваш зарегистрированный Discord.'
    - ''
    - ' &aНажмите на кнопку в сообщении, чтобы подтвердить вашу личность.'
    - ''
    dm:
      configure:
        too-recent:
          title: Слишком новый аккаунт
          description: Вы не можете привязать Discord, так как ваш аккаунт был создан слишком недавно.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
        invalid:
          title: Неверный код
          description: Извините, но введенный токен недействителен или не существует.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
        success:
          title: Discord привязан
          description: Ваш Discord был успешно привязан.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
      verify:
        title: Подтвердите аутентификацию вашего аккаунта.
        description: |-
          Для доступа к вашему аккаунту @player требуется подтверждение аутентификации.

          Если это были не вы, отклоните операцию и немедленно смените пароль.
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
        allow: Разрешить
        deny: Отклонить
      recover:
        title: Запрошено восстановление пароля.
        description: |-
          Запрос на восстановление пароля был отправлен с вашего аккаунта @player.

          Если это были не вы, отклоните операцию и немедленно смените пароль.
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
        allow: Разрешить
        deny: Отклонить
      new-password:
        title: Новый пароль для @player
        description: |-
          Для вашего аккаунта был сгенерирован новый пароль:
          `{0}`
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
      password-changed:
        title: Пароль изменен для @player
        description: |-
          Ваш пароль был изменен на:
          `{0}`
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
  email:
    invalid-email: '&cВведена неверная почта.'
    not-allowed: '&cДомен выбранной почты не разрешен.'
    server-email: '&cВы не можете использовать адрес почты сервера.'
    warn-message:
    - ''
    - ' &aСистема безопасности email'
    - ' &aИспользйте команду &f/email associate <ваш email> &aчтобы улучшить вашу безопасность.'
    - ' &aС привязкой к email, вы избежите взлома своего аккаунта.'
    - ''
    email-required:
    - ''
    - ' &7Текущий сервер требует, чтобы вы привязали'
    - ' &aдействительный email &7для завершения регистрации.'
    - ''
    - ' &6Пожалуйста, выполните &f/email add <ваш email>&6.'
    - ''
    address-changed:
    - ''
    - ' &7Вам нужно подтвердить вход в аккаунт.'
    - ' &7Сообщение безопасности было отправлено на вашу зарегистрированную почту.'
    - ''
    - ' &aИспользуйте команду &f/email <code> &aдля завершения аутентификации.'
    - ''
    smtp:
      configure:
        subject: Подтверждение учетной записи @player
        content:
        - <h1>
        - ' Здравствуйте, @player!'
        - </h1>
        - <p>
        - ' Чтобы завершить процесс регистрации email, используйте команду <strong>"/email @code"</strong>.'
        - </p>
        - <p>
        - ' Если это были не Вы, проигнорируйте это письмо.'
        - </p>
      verify:
        subject: Подтверждение входа в аккаунт @player
        content:
        - <h1>
        - ' Здравствуйте, @player!'
        - </h1>
        - <p>
        - ' Чтобы авторизироваться на сервере, используйте команду <strong>"/email @code"</strong>.'
        - </p>
        - <p>
        - ' Если это были не Вы, смените пароль <strong>НЕМЕДЛЕННО</strong>.'
        - </p>
      recover:
        subject: Восстановление аккаунта @player
        content:
        - <h1>
        - ' Привет, @player!'
        - </h1>
        - <p>
        - ' Для восстановления учетной записи воспользуйтесь командой <strong>"/email <new password> @code"</strong>.'
        - </p>
        - <p>
        - ' Если это были не Вы, проигнорируйте это письмо.'
        - </p>
      new-password:
        subject: Новый пароль для @player
        content:
        - <h1>
        - ' Привет, @player!'
        - </h1>
        - <p>
        - ' Для вашего аккаунта был сгенерирован новый пароль: {0}'
        - </p>
      password-changed:
        subject: Пароль изменен для @player
        content:
        - <h1>
        - ' Привет, @player!'
        - </h1>
        - <p>
        - ' Ваш пароль был изменен на: {0}'
        - </p>

bedrock:
  forms:
    login:
      title: Авторизация
      content:
      - Приветствую, @player!
      - 'Для входа на сервер, введите ваш пароль ниже:'
      - ''
      - '[Пароль//Введите ваш пароль]'
      - ''
    register:
      title: Регистрация
      content:
      - Приветствую, @player!
      - Для игры на сервере, требуется зарегистрироваться.
      - Пожалуйста введите ваш пароль ниже.
      - ''
      - '[Пароль//Введите ваш пароль]'
      - '[Подтверждение//Введите ещё раз ваш пароль]'
      - ''

dialogs:
  login:
    title: '&#ffdb60Введите ваш пароль'
    body:
    - '&6Добро пожаловать, &f@player&6!'
    - ''
    - '&#ffdb60Пожалуйста, введите свой пароль для входа на сервер.'
    - ''
    inputs:
      password: Пароль
    buttons:
      login: Вход
      recover: Забыл пароль
      cancel: Выход
  register:
    title: '&#ffdb60Создание пароля'
    body:
    - '&6Добро пожаловать, &f@player&6!'
    - ''
    - '&#ffdb60Вы должны &bсоздать пароль &#ffdb60чтобы войти на сервер.'
    - ''
    - '&#ffdb60Пожалуйста, заполните поля ниже, чтобы продолжить.'
    - ''
    inputs:
      password1: Пароль
      password2: Подтверждение
    buttons:
      register: Создать аккаунт
      cancel: Выйти

title:
  before-login:
    title: '&6&lДобро пожаловать!'
    subtitle: '&7Используйте: /login <your password>'
    delays:
      fadeIn: 6
      stay: 9999
      fadeOut: 6
  before-register:
    title: '&6&lДобро пожаловать!'
    subtitle: '&7Используйте: /register <your password> <password confirmation>'
    delays:
      fadeIn: 6
      stay: 9999
      fadeOut: 6
  after-login:
    title: ''
    subtitle: '&6Вы успешно зашли!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  after-register:
    title: ''
    subtitle: '&6Вы успешно зарегистрировались!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  incorrect-password:
    title: ''
    subtitle: '&cНеправильный пароль!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  already-login:
    title: ''
    subtitle: '&fВы &cуже &fвошли в аккаунт!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  already-registered:
    title: ''
    subtitle: '&fВы &6уже &fзарегистрированы!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  passwords-dont-match:
    title: ''
    subtitle: '&fПароль &cне совпадает &fс предыдущим!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  session-login:
    title: ''
    subtitle: '&fВаша сессия &aактивна&f.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  premium-login:
    title: ''
    subtitle: '&fВаш аккаунт &6лицензионный&f, вы успешно зашли.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  bedrock-login:
    title: ''
    subtitle: '&eДоступ через Bedrock, успешно вошел в систему.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  security-warning:
    title: ''
    subtitle: '&fСообщение с &cпредупреждением&f безопасности отправлено в чат'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  unconfirmed-message:
    title: ''
    subtitle: '&c!! &eВ чате есть неподтвержденное сообщение'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
