####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                      A practical, secure and friendly authentication plugin                  | #
# |                                                                                              | #
# |                                © 2026 - Powered by nickuc.com                                | #
# |                                                                                              | #
# |              List of translation authors: https://crowdin.com/project/nlogin/members         | #
# |                                                                                              | #
# |  New options are not automatically added in this file. Default values are used               | #
# |  if an option is not found.                                                                  | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

pending:
  login: '&eИзползвайте командата &7/login <парола>&e.'
  register: '&eИзползвайте командата &7/register <парола> <парола>&e.'
  action-bar:
    singular: '&cИмате {0} секунда, за да {login///register}.'
    plural: '&cИмате {0} секунди, за да {login///register}.'

success:
  login: '&aВлезнахте успешно.'
  register: '&aРегистрацията ви е успешна.'
  session: '&aВашата сесия за влизане беше продължена.'
  premium: '&aАвтоматично сте влезли, защото използвате premium акаунт.'
  bedrock: '&aВлезли сте автоматично, тъй като достъпвате от акаунт на Bedrock.'
  change-password: '&aПаролата ви беше успешно променена.'
  reload: '&eПлъгинът беше успешно презареден.'
  kick:
    unregister: '&aВие бяхте успешно отписани.'
    marked-offline: '&7Вашият акаунт беше маркиран като &6офлайн&7, моля, присъединете се отново.'
    challenge-premium: '&7За да потвърдите, че използвате &apremium акаунт&7, моля, влезте отново.'

error:
  not-registered: '&cТова потребителско име все още не е регистрирано.'
  offline: '&cЖеланият играч е офлайн.'
  address-limit: '&cИзчерпахте лимита на акаунтите за IP адреса.'
  database: '&cСъжалявам, тази операция върху базата данни не може да бъде завършена. Проверете конзолата за повече информация.'
  command:
    usage: '&cТрябва да използвате {0}.'
    no-permission: '&cНямате права да изпълните тази команда.'
    player-required: '&cТази команда е забранена през конзолата.'
    console-required: '&cТази команда може да бъде използвана само чрез конзолата.'
    account-collision:
    - '&fПовече от един акаунт има прякор &a{0}&f:'
    - '&8⋆ &7{1} {2}'
    - ''
    - '&c‼ &eИзпълнете командата отново, като се уверите, че използвате прякора, съответстващ на желания тип акаунт.'
    arguments:
      password: парола
      current-password: текуща парола
      new-password: нова парола
  already:
    login: '&cВече сте влезли.'
    login-other: '&cТози играч вече е влезнал.'
    registered: '&cТова потребителско име вече е регистрирано.'
    premium: '&cВашият акаунт вече е маркиран като premium.'
  password:
    same-as-current: '&cВъведената парола е същата като текущата.'
    too-large: '&cВъведената парола е твърде дълга.'
    too-small: '&cВъведената парола е твърде къса.'
    not-secure: '&cВъведената парола не отговаря на изискванията за сигурност. Моля, включете число, главни и малки букви и специален символ.'
    do-not-match: '&cПаролите не съвпадат.'
    require-confirmation: '&cТрябва да потвърдите паролата си.'
    incorrect: '&cГрешна парола. Моля, опитайте отново.'
  kick:
    incorrect-password: '&cВъвели сте грешна парола.'
    wait-server-start: |-
      &cСървърът още не е стартирал напълно.
      &cИзчакайте малко, за да се свържете.
    account-blocked: |-
      &cВашият адрес е блокиран поради заподозрена инвазия.&r
      &r&cОставащо време на блокиране: {0}
    account-unregistered: |-
      &cТози сървър не приема нови регистрации на акаунти.

      &cЗа повече информация се свържете с администрацията на сървъра.
    invalid-nickname: '&cПотребителското ви име е невалидно, премахнете интервали, символи и невалидни символи от името си.'
    bedrock-nickname: '&cИзбраният префикс на потребителското име &f("{0}") &cе ограничен за играчи на Bedrock.'
    bedrock-unlinked: |-
      &cИзбраният прякор &f("{0}") &cе запазен за premium Java играч.

      &eЗа да получите достъп до този акаунт, свържете Java акаунта си с вашия Bedrock акаунт чрез командата &f/linkaccount&e.
    transferred-nickname: |-
      &cИзбраното име &f("{0}") &cбеше резервирано и прехвърлено към акаунт, използващ същия UUID.

      &eЗа да влезете, моля, използвайте друго име.
    already-online: '&cТози играч вече е на линия.'
    unknown-hostname: |-
      &4[nLogin] Използваното име на хоста &f({0}) &4не е дефинирано в конфигурацията.
      &r
      &r&cАко това е валиден IP адрес, моля, добавете го в най-подходящата категория в раздела на конфигурацията &f"premium.username-appender"&c.
      &r
      &r&eЗа повече информация, вижте ръководството за добавяне на потребителско име:
      &r&bhttps://docs.nickuc.com/nlogin/username-appender
    premium-not-logged: |-
      &7Потребителското име &6{0} &7е свързано с потвърден &apremium акаунт&7, но сесията ви е &cизтекла&7.

      &eАко сте собственик на този акаунт, рестартирайте Minecraft и влезте отново.
    premium-challenge: |-
      &eПо време на последния ви опит за влизане не успяхме да удостоверим акаунта ви.

      &fАко използвате &apremium &fакаунт, рестартирайте Minecraft и влезте отново.

      &fАко акаунтът ви е &coffline&f, моля, влезте отново, за да завършите проверката.
    timeout:
      login: '&cВие отнемате твърде много време за влизане.'
      register: '&cВие отнемате твърде много време за регистрация.'

notification:
  all-viewed: '&aВсички уведомления са видяни.'
  premium-question:
  - ''
  - ' &eИзползвате ли премиум акаунт?'
  - ' &7(След като кликнете ДА или НЕ, ще трябва да влезете отново в сървъра!)'
  - ''
  premium-transfer-question:
  - ''
  - ' &eВече има регистриран offline акаунт с прякор &f@player&e.'
  - ''
  - ' &6Искате ли да прехвърлите данните от този акаунт или да създадете нов акаунт?'
  - ''
  - ' &c‼ &eЩе трябва да се удостоверите, за да потвърдите собствеността на акаунта.'
  - ''
  premium-transfer-confirmation:
  - ''
  - ' &6Искате ли да потвърдите прехвърлянето на данните от &f@player &6към вашия premium акаунт?'
  - ''
  - ' &c‼ &eПри потвърждаване на прехвърлянето ще бъдете изключени от сървъра.'
  - ''
  password-update:
  - ''
  - ' &eВашата парола трябва да бъде нулирана.'
  - ''
  - ' &7Моля, променете паролата си с командата по-долу:'
  - ' &f/changepass <текуща парола> <нова парола>'
  - ''
  button:
    confirm-read:
      text: '&a[✔ Потвърди прочитането]'
      hover: null
    yes-btn:
      text: '&a[✔ Да]'
      hover: null
    no-btn:
      text: '&c[✖ Не]'
      hover: null
    new-account:
      text: '&a[Нов акаунт]'
      hover: null
    transfer-data:
      text: '&9[Прехвърли данни]'
      hover: null

2fa:
  not-registered: '&cНямате {0} акаунт.'
  already-registered: '&cВече сте регистрирали вашият {0}.'
  register-limit: '&cИзчерпахте лимитите на акаунтите със същия {0}.'
  unregistered: '&eВашият {0} беше успешно отписан.'
  incorrect-code: '&cГрешен код. Моля, опитайте отново.'
  rate-limit: '&cПревишен лимит. Моля, изчакайте {0} минути, за да опитате отново.'
  confirmed-account: '&aВашият {0} акаунт беше успешно регистриран.'
  confirmation-message-sent: |-
    &7Изпратен е код за потвърждение до вашия &6{0}&7.
    &8(&f{1}&8).
  command-delay: '&cИзчакайте малко преди да изпълните тази команда отново.'
  help-command:
  - ''
  - ' &fСтатус: [&a{2} регистрирани//&c{2} нерегистрирани]&f.'
  - ''
  - ' [&8⋆ &7/{0} add: &fРегистрирайте вашият {1}.]'
  - ' [&8⋆ &7/{0} remove: &fПремахнете вашият {1}.]'
  - ' [&8⋆ &7/{0} recover: &fВъзстановете акаунта си.]'
  - ' [&8⋆ &7/{0} 2fa: &fВключва/изключва двуфакторната аутентикация.]'
  - ''
  recover-command:
  - ''
  - ' &eИзберете метод за възстановяване:'
  - ' [&8⋆ &7{0}: &f/{1} recover]'
  - ''
  switch:
    enabled: '&aФункцията за двуфакторна аутентикация е активирана.'
    disabled: '&cФункцията за двуфакторна аутентикация е деактивирана.'
  recover:
    not-equal: '&cПредоставеният {0} не съвпада с регистрирания.'
    message-sent: '&aИзпратено е съобщение за възстановяване до вашия асоцииран акаунт.'
    change-password: '&aПаролата ви беше автоматично променена на &f''{0}''&a.'
  discord:
    account-linked: |-
      &aКонфигурацията в Discord е актуализирана успешно.
      &aВие бяхте свързани с акаунта на &f{0} &a.
    confirm-account:
    - ''
    - ' &7За да завършите свързването, трябва да потвърдите вашия &bDiscord &7акаунт.'
    - ' &7Присъединете се към &b{0} &7и въведете'
    - ' &7командата на лично съобщение на бота &f{1} &7.'
    - ''
    - ' [&c&lНатиснете това съобщение, за да получите командата с кода.]'
    - ''
    warn-message:
    - ''
    - ' &7Изпълнете командата &f/discord add &7за да регистрирате'
    - ' &7вашия &9Discord&7. По този начин'
    - ' &7вероятността от хакване.'
    - ''
    discord-required:
    - ''
    - ' &7Текущият сървър изисква свързване с'
    - ' &aDiscord акаунт &7за да завърши регистрацията.'
    - ''
    - ' &6&lЗадължително изпълнете тази команда в чата &8: &f/discord add'
    - ''
    address-changed:
    - ''
    - ' &7Трябва да потвърдите влизането в акаунта си.'
    - ' &7Беше изпратено сигурностно съобщение до вашия регистриран Discord.'
    - ''
    - ' &aКликнете бутона за съобщение, за да потвърдите своята идентичност.'
    - ''
    dm:
      configure:
        too-recent:
          title: Твърде нов акаунт
          description: Не можете да свържете вашия Discord, защото акаунтът ви е създаден твърде наскоро.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
        invalid:
          title: Грешен код
          description: За съжаление, въведеният от вас токен е невалиден или не съществува.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
        success:
          title: Discord свързан
          description: Вашият Discord е успешно свързан.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
      verify:
        title: Потвърдете вашият акаунт
        description: |-
          Изисква се потвърждение на аутентикацията, за да получите достъп до вашият акаунт @player.

          Ако това не е било вие, откажете операцията и незабавно променете паролата си.
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
        allow: Позволявам
        deny: Отказвам
      recover:
        title: Изискана е заявка за възстановяване на паролата.
        description: |-
          Беше изискана заявка за възстановяване на паролата от вашият акаунт @player.

          Ако това не е било вие, откажете операцията и незабавно променете паролата си.
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
        allow: Позволявам
        deny: Отказвам
      new-password:
        title: Нова парола за @player
        description: |-
          Нова парола беше генерирана за вашия акаунт:
          `{0}`
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
      password-changed:
        title: Паролата е променена за @player
        description: |-
          Вашата парола беше променена на:
          `{0}`
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
  email:
    invalid-email: '&cВъведеният имейл е невалиден.'
    not-allowed: '&cДомейнът на избрания имейл не е позволен.'
    server-email: '&cНе можете да използвате имейл на сървъра.'
    warn-message:
    - ''
    - ' &7Изпълнете командата &f/email associate &7за да регистрирате'
    - ' &7вашия &9имейл&7. Така ще намалите'
    - ' &7вероятността от хакване.'
    - ''
    email-required:
    - ''
    - ' &7Текущият сървър изисква свързване с'
    - ' &aвалиден имейл &7за да завърши регистрацията.'
    - ''
    - ' &6Моля, изпълнете &f/email add <вашият имейл>&6.'
    - ''
    address-changed:
    - ''
    - ' &7Трябва да потвърдите влизането в акаунта си.'
    - ' &7Беше изпратено сигурностно съобщение до вашия регистриран имейл.'
    - ''
    - ' &aИзползвайте командата &f/email <code> &aза да завършите удостоверяването.'
    - ''
    smtp:
      configure:
        subject: Потвърждение на акаунт @player
        content:
        - <h1>
        - ' Здравейте, @player!'
        - </h1>
        - <p>
        - ' За да завършите процеса за регистрация на имейл, използвайте командата <strong>"/email @code"</strong>.'
        - </p>
        - <p>
        - ' Ако това не сте били вие, игнорирайте това съобщение.'
        - </p>
      verify:
        subject: Потвърждение на влизане в акаунт @player
        content:
        - <h1>
        - ' Здравейте, @player!'
        - </h1>
        - <p>
        - ' За да се аутентифицирате на сървъра, използвайте командата <strong>"/email @code"</strong>.'
        - </p>
        - <p>
        - ' Ако това не сте били вие, променете паролата си <strong>НЕЗАБАВНО</strong>.'
        - </p>
      recover:
        subject: Възстановяване на акаунт @player
        content:
        - <h1>
        - ' Здравейте, @player!'
        - </h1>
        - <p>
        - ' За да възстановите акаунта си, използвайте командата <strong>"/email <нова парола> @code"</strong>.'
        - </p>
        - <p>
        - ' Ако това не сте били вие, игнорирайте това съобщение.'
        - </p>
      new-password:
        subject: Нова парола за @player
        content:
        - <h1>
        - ' Здравейте, @player!'
        - </h1>
        - <p>
        - ' Нова парола беше генерирана за вашия акаунт: {0}'
        - </p>
      password-changed:
        subject: Паролата е променена за @player
        content:
        - <h1>
        - ' Здравейте, @player!'
        - </h1>
        - <p>
        - ' Вашата парола беше променена на: {0}'
        - </p>

bedrock:
  forms:
    login:
      title: Удостоверяване
      content:
      - Добре дошли, @player!
      - 'За да влезете, моля, въведете паролата си в полето по-долу:'
      - ''
      - '[Парола//Въведете паролата си]'
      - ''
    register:
      title: Регистрация
      content:
      - Добре дошли, @player!
      - За да играете на сървъра, трябва да създадете парола.
      - Моля, въведете желаната парола в полето по-долу.
      - ''
      - '[Парола//Въведете паролата си]'
      - '[Потвърждение//Потвърдете паролата си]'
      - ''

dialogs:
  login:
    title: '&#ffdb60Въведете паролата си'
    body:
    - '&6Добре дошъл, &f@player&6!'
    - ''
    - '&#ffdb60Моля, въведете паролата си, за да влезете в сървъра.'
    - ''
    inputs:
      password: Парола
    buttons:
      login: Влизане
      recover: Забравена парола
      cancel: Изход
  register:
    title: '&#ffdb60Създаване на парола'
    body:
    - '&6Добре дошъл, &f@player&6!'
    - ''
    - '&#ffdb60Трябва да &bсъздадете парола &#ffdb60, за да влезете в сървъра.'
    - ''
    - '&#ffdb60Моля, попълнете полетата по-долу, за да продължите.'
    - ''
    inputs:
      password1: Парола
      password2: Потвърждение
    buttons:
      register: Създаване на акаунт
      cancel: Изход

title:
  before-login:
    title: '&a&lДОБРЕ ДОШЛИ!'
    subtitle: '&7Напишете: /login <вашата парола>'
    delays:
      fadeIn: 6
      stay: 9999
      fadeOut: 6
  before-register:
    title: '&a&lДОБРЕ ДОШЛИ!'
    subtitle: '&7Напишете: /register <вашата парола> <потвърждение на паролата>'
    delays:
      fadeIn: 6
      stay: 9999
      fadeOut: 6
  after-login:
    title: ''
    subtitle: '&aУспешно влязохте!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  after-register:
    title: ''
    subtitle: '&aУспешно се регистрирахте!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  incorrect-password:
    title: ''
    subtitle: '&cГрешна парола!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  already-login:
    title: ''
    subtitle: '&cВече сте влезли!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  already-registered:
    title: ''
    subtitle: '&cВече сте регистрирани!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  passwords-dont-match:
    title: ''
    subtitle: '&cПаролите не съвпадат!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  session-login:
    title: ''
    subtitle: '&eВашата сесия за влизане продължава.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  premium-login:
    title: ''
    subtitle: '&eВашият акаунт е premium, успешно сте влезли.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  bedrock-login:
    title: ''
    subtitle: '&eВлезли сте чрез Bedrock, успешно влезли.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  security-warning:
    title: ''
    subtitle: '&cИзпратено е ново сигурностно предупреждение в чата'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  unconfirmed-message:
    title: ''
    subtitle: '&c‼ &eИма непотвърдено съобщение в чата'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
