####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                                  一款实用、安全、友好的身份验证插件                                | #
# |                                                                                              | #
# |                                © 2026 - 由 nickuc.com 提供支持                                 | #
# |                                                                                              | #
# |                                                                                              | #
# |  为了更好地理解这个文件,请参阅我们的文档:                                                           | #
# |   ==> https://docs.nickuc.com/nlogin/                                                        | #
# |                                                                                              | #
# |  新选项不会自动添加到此文件中. 如果找不到                                                           | #
# |  选项则使用默认值.                                                                              | #
# |                                                                                              | #
# |  译者:                                                                                        | #
# |   - jhqwqmc                                                                                  | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# 配置文件的版本
language-version: 11

# 设置电子邮件是否可以用作双因素认证
enable: false

authentication:
  # 电子邮件
  email: "yourserver@domain.com"
  # 来自
  from: "您的服务器"
  # 用户
  user: ""
  # 密码
  password: ""

  # 字符设置
  charset: "UTF-8"
  # Mime类型
  mimetype: "text/html"

  # 邮件发送地址
  host: "smtp.gmail.com"
  # 邮件发送端口
  port: 587

  # 加密
  #
  # - 可用选项:
  #  |=> AUTO
  #  |=> TLS
  #  |=> SSL
  encryption: AUTO

  # 调试模式
  debug: false

linking:
  # 设置是否应将链接推荐给玩家
  recommend: true

  # 定义完成链接后是否启用 2FA
  enable-2fa: true

  required:
    # 设置是否需要链接电子邮件才能进行身份验证
    enable: false

    # 设置正版玩家是否还需要链接电子邮件来验证自己的身份
    enable-for-premium: true

    # 设置基岩版玩家是否需要关联电子邮件进行身份验证
    enable-for-bedrock: true

account:
  # 设置可以链接同一电子邮件的最大帐户数
  limit: 1

  # 定义是否应在帐户恢复过程之后创建新密码。
  # - 如果禁用此选项，将设置随机密码
  force-password-update: false

  # 设置允许的域名列表
  # - 如果未设置域名,则允许所有域名
  allowed-domains: []

  # 定义拒绝域名列表
  denied-domains: []