####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                      A practical, secure and friendly authentication plugin                  | #
# |                                                                                              | #
# |                                © 2026 - Powered by nickuc.com                                | #
# |                                                                                              | #
# |                                                                                              | #
# |  Для лучшего понимания этого файла смотрите нашу документацию:                               | #
# |   ==> https://docs.nickuc.com/nlogin/                                                        | #
# |                                                                                              | #
# |  Сообщество в VK:                                                                            | #
# |   ==> https://www.nickuc.com/vk                                                              | #
# |                                                                                              | #
# |  Новые опции не добавляются автоматически в этот файл. Если опция не найдена,                | #
# |  используются значения по умолчанию.                                                         | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Установите версию файла.
language-version: 5

#     ___      _        ___               __        __       ___
#    / __\    /_\      / __\    /\ /\    /__\    /\ \ \     /   \
#   /__\//   //_\\    / /      / //_/   /_\     /  \/ /    / /\ /
#  / \/  \  /  _  \  / /___   / __ \   //__    / /\  /    / /_//
#  \_____/  \_/ \_/  \____/   \/  \/   \__/    \_\ \/    /___,'

# Настройки, связанные с внутренними серверами.
backend:
  # Задает список серверов аутентификации.
  # - Вы должны ввести этот список ВСЕХ серверов, на которых установлен nLogin.
  # - Большинство серверов используют либо сервер аутентификации, либо главное лобби.
  # - Для получения дополнительной информации обратитесь к учебнику:
  #  ==> https://docs.nickuc.com/nlogin/proxy
  auth-servers:
    - 'lobby'

  # Определяет, должен ли прокси проверять, правильно ли настроены серверы аутентификации.
  # - Если вы используете сервер без nLogin (например, серверы limbo, не основанные на Spigot)
  #   рекомендуется отключить эту опцию.
  check-ack-message: true

#     __      __       ___     _____      __      __      ___    _____
#    /__\    /__\     /   \    \_   \    /__\    /__\    / __\  /__   \
#   / \//   /_\      / /\ /     / /\/   / \//   /_\     / /       / /\/
#  / _  \  //__     / /_//   /\/ /_    / _  \  //__    / /___    / /
#  \/ \_/  \__/    /___,'    \____/    \/ \_/  \__/    \____/    \/

# Настройки перенаправления сервера.
redirect:
  # Определяет, будет ли выполняться перенаправление перед подключением к серверам аутентификации.
  # - Например, когда игрок, которому не нужно проходить аутентификацию, заходит на прокси-сервер,
  #   он автоматически подключается к серверу, который учитывает указанные ниже параметры.
  use-fast-redirect: true

  # Определяет, должно ли перенаправление первого сервера быть перезаписано nLogin.
  # - Эта опция предотвращает обход игроками сервера аутентификации
  #   и восстанавливает первый сервер, предоставленный прокси.
  override-first-server: true

  # Устанавливает время ожидания (в миллисекундах) при переключении сервера.
  connect-delay: 500

  # Устанавливает время ожидания (в миллисекундах) для повторного подключения к серверу при разрыве соединения.
  retry-delay: 5000

  last-server:
    # Определяет, должен ли плагин перенаправлять игроков на последний подключенный сервер.
    # - Если последний подключенный сервер больше не существует, будет выбран случайный сервер из опции "after-auth.servers".
    enable: false

    # Определяет, какие серверы будут игнорироваться при перенаправлении.
    ignored: []

  after-auth:
    # Определяет, должны ли игроки автоматически перенаправляться на другие серверы после аутентификации.
    enable: false

    # Определяет, на какие серверы должны быть перенаправлены игроки.
    # - При вводе более одного пункта сервер будет выбран случайным образом.
    servers:
      - "lobby1"
      - "lobby2"