####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                                  一款实用、安全、友好的身份验证插件                                | #
# |                                                                                              | #
# |                                © 2026 - 由 nickuc.com 提供支持                                 | #
# |                                                                                              | #
# |                                                                                              | #
# |  新选项不会自动添加到此文件中. 如果找不到                                                           | #
# |  选项则使用默认值.                                                                              | #
# |                                                                                              | #
# |  译者:                                                                                        | #
# |   - jhqwqmc                                                                                  | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# 配置文件的版本
language-version: 11

#     ___      _        ___               __        __       ___
#    / __\    /_\      / __\    /\ /\    /__\    /\ \ \     /   \
#   /__\//   //_\\    / /      / //_/   /_\     /  \/ /    / /\ /
#  / \/  \  /  _  \  / /___   / __ \   //__    / /\  /    / /_//
#  \_____/  \_/ \_/  \____/   \/  \/   \__/    \_\ \/    /___,'

# 与后端服务器相关的设置
backend:
  # 设置身份验证服务器列表
  # - 你必须输入此列表中安装了 nLogin 的所有服务器
  # - 大多数服务器使用身份验证服务器或主大厅
  # - 有关更多信息,请转到教程:
  #  ==> https://docs.nickuc.com/nlogin/proxy
  auth-servers:
    - 'lobby'

  # 设置代理是否应检查身份验证服务器是否已正确配置
  # - 如果你使用的服务器没有 nLogin(例如,不基于 Spigot 的 Limbo 服务器)
  #   建议禁用此选项
  check-ack-message: true

#     __      __       ___     _____      __      __      ___    _____
#    /__\    /__\     /   \    \_   \    /__\    /__\    / __\  /__   \
#   / \//   /_\      / /\ /     / /\/   / \//   /_\     / /       / /\/
#  / _  \  //__     / /_//   /\/ /_    / _  \  //__    / /___    / /
#  \/ \_/  \__/    /___,'    \____/    \/ \_/  \__/    \____/    \/

# 服务器重定向设置
redirect:
  # 定义在连接身份验证服务器之前是否进行重定向。
  # - 例如，当不需要验证的玩家进入代理服务器时，
  #   他们会自动连接到符合以下选项的服务器。
  use-fast-redirect: true

  # 设置第一台服务器的重定向是否应被 nLogin 覆盖
  # - 此选项可防止玩家绕过身份验证服务器
  #   并恢复代理提供的第一台服务器
  override-first-server: true

  # 设置切换服务器时的等待时间(以毫秒为单位)
  connect-delay: 500

  # 设置连接失败时重新连接服务器的等待时间(以毫秒为单位)
  retry-delay: 5000

  last-server:
    # 设置插件是否应将玩家重定向到最后连接的服务器
    # - 如果最后连接的服务器不再存在,则会从"after-auth.servers"选项中选择一个随机服务器
    enable: false

    # 定义重定向将忽略哪些服务器
    ignored: []

  after-auth:
    # 设置身份验证后是否应将玩家自动转发到其他服务器
    enable: false

    # 设置玩家应该被转发到哪些服务器
    # - 当输入超过一项时,服务器将被随机选择
    servers:
      - "lobby1"
      - "lobby2"