update:
  stable: '&aСтабилна'
  latest: '&bНай-нова'

notification:
  setup:
    select-language:
    - ''
    - ' &eОткрихме, че използвате език &6{0}&e.'
    - ''
    - ' &6Искате ли да използвате този език за nLogin?'
    - ''
    - ' &c‼ &eТова засяга езика на всички играчи!'
    - ''
    permission-required:
    - ''
    - ' &eЗа да конфигурирате nLogin, трябва да станете &cадминистратор&e.'
    - ''
    - ' &6Добавете разрешението &f"{0}" &6към вашия plugin за разрешения.'
    - ''
    - ' &c‼ &eНастройката ще продължи веднага щом разрешението бъде добавено.'
    - ''
    welcome-message:
    - ''
    - ' &aБлагодарим ви много, че избрахте nLogin! :)'
    - ''
    - ' &6За вашата безопасност, моля, прочетете съобщението по-долу:'
    - '  &cНикога не изтегляйте nLogin от неизвестни източници.'
    - '  &cМодифицирана версия може да съдържа злонамерен софтуер.'
    - ''
    - ' &aДоверени източници:'
    - '  &7Уебсайт: &fnickuc.com'
    - '  &7GitHub: &fgithub.com/nickuc-com'
    - '  &7Инсталатор на OpeNLogin (от &fSpigot &7или &fGitHub&7)'
    - ''
    - ' &aОфициална поддръжка:'
    - '  &7Документация: &fdocs.nickuc.com/nlogin/'
    - '  &7Discord: &fnickuc.com/discord'
    - '  &7Имейл: &fsupport@nickuc.com'
    - ''
    configure-version-channel:
    - ''
    - ' &6Изберете предпочитания канал за версии.'
    - ''
    - ' &c‼ &eМожете да промените това по-късно, като изпълните &f{0}&e.'
    - ''
    configure-auto-or-manual-updates:
    - ''
    - ' &6Изберете предпочитания метод за актуализация.'
    - ''
    - ' &c‼ &eМожете да промените това по-късно, като изпълните &f{0}&e.'
    - ''
    configure-password-algorithm:
    - ''
    - ' &6Изберете предпочитания тип криптиране за паролите.'
    - ''
    - ' &c‼ &eМожете да промените тази опция ръчно по-късно в &fconfig.yml&e.'
    - ''
    enable-dialogs:
    - ''
    - ' &6Искате ли да използвате менютата (dialogs) като интерфейс за удостоверяване?'
    - ''
    - ' &eDialogs заменят удостоверяването чрез команди с персонализируеми менюта.'
    - ''
    - ' &c‼ &eТази функция работи само за клиенти с версия 1.21.6 или по-висока.'
    - ''
    configure-dialogs:
    - ''
    - ' &6Изберете предпочитания начин за показване на dialogs.'
    - ''
    - ' &c‼ &eМожете да промените тази опция ръчно в &fconfig.yml&e.'
    - ''
    configure-bungeeguard:
    - ''
    - ' &6Искате ли да конфигурирате BungeeGuard+ на сървъра?'
    - ''
    - ' &c‼ &eПрепоръчително е да инсталирате BungeeGuard+ в следните случаи:'
    - '  &8⋆ &eИзползвате какъвто и да е proxy, базиран на BungeeCord.'
    - '  &8⋆ &eИзползвате Velocity, но forwarding &f"MODERN" &eне може да се използва.'
    - ''
    - ' &c‼ &eЩе трябва да инсталирате BungeeGuard+ JAR на всички сървъри.'
    - ''
    start-premium-configuration:
    - ''
    - ' &aПоздравления за покупката на &6⭐ nLogin Premium'
    - ''
    - ' &6Ето новите отключени функции:'
    - ''
    - '  &8⋆ &eАвтоматично влизане &7за потребители с premium Minecraft.'
    - '  &8⋆ &eДвустепенно &7удостоверяване чрез Discord и имейл.'
    - '  &8⋆ &eСесии за влизане &7при влизане с IP адрес.'
    - '  &8⋆ &eПоддръжка с &7по-висок приоритет.'
    - '  &8⋆ &eЕтикет за клиент &7в Discord групата.'
    - ''
    configure-username-appendix:
    - ''
    - ' &6Искате ли да активирате наставка за premium/offline играчи?'
    - ''
    - ' &c‼ &eЗа повече информация относно тази функция посетете: &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    configure-username-appendix-legacy-versions:
    - ''
    - ' &6Наставката за premium/offline играчи не може да се добави автоматично за версии 1.18.2 или по-ниски.'
    - ''
    - ' &eЩе трябва ръчно да конфигурирате два различни IP адреса за premium и offline играчи.'
    - ''
    - ' &c‼ &eЗа повече информация относно тази функция посетете: &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    enable-restrict-premium-nicknames:
    - ''
    - ' &6Да се ограничи ли регистрацията на offline играчи, използващи premium прякори? &e(за нови акаунти)'
    - ''
    - ' &c‼ &eOffline играчите няма да могат да използват &fpremium прякор (напр. Notch)&e, дори ако името е налично за регистрация.'
    - ''
    enable-challenge-premium-nicknames:
    - ''
    - ' &6Да се открива ли дали играчите използват premium акаунт? &e(чрез прякора)'
    - ''
    - ' &c‼ &eOffline играчите може да получат неперсонализируемо съобщение &f"Invalid session" &eпри първото влизане в сървъра.'
    - ''
    enable-premium-question:
    - ''
    - ' &6Да се открива ли дали играчите използват premium акаунт? &e(чрез интерактивен въпрос)'
    - ''
    - ' &c‼ &eТази опция се препоръчва, ако искате да сте сигурни, че premium играчите получават Mojang UUID.'
    - ''
    skip-premium-register:
    - ''
    - ' &6Да се пропусне ли заявката за регистрация на парола за &bpremium играчи&6?'
    - ''
    - ' &c‼ &eПрепоръчително е да деактивирате тази опция, ако паролата на играчите се използва в уеб интеграция (напр. уебсайт на сървъра).'
    - ''
    skip-bedrock-register:
    - ''
    - ' &6Да се пропусне ли заявката за регистрация на парола за &cBedrock играчи&6?'
    - ''
    - ' &c‼ &eПрепоръчително е да деактивирате тази опция, ако паролата на играчите се използва в уеб интеграция (напр. уебсайт на сървъра).'
    - ''
    nantibot-recommendation:
    - ''
    - ' &6Препоръчваме да инсталирате &fnAntiBot&6, за да предотвратите'
    - ' &6атака на сървъра ви от ботове.'
    - ''
    - ' &c‼ &eЗа повече информация относно този plugin &6кликнете тук&e.'
    - ''
    nchat-recommendation:
    - ''
    - ' &6Препоръчваме да инсталирате &fnChat&6,'
    - ' &6chat plugin, който напълно заменя Legendchat.'
    - ''
    - ' &c‼ &eЗа повече информация относно този plugin &6кликнете тук&e.'
    - ''
    recommend-spawn-set:
    - ''
    - ' &6Координатите на играчите &cНЯМА &6да бъдат защитени преди влизане.'
    - ''
    - ' &c‼ &eЗадайте безопасна spawn точка чрез командата &f{0}&e.'
    - ''
    finish-configuration:
    - ''
    - ' &6Потвърдете, за да излезете от режима на настройка и запазите всички промени.'
    - ''
    - ' &c‼ &eВсички играчи ще бъдат изключени след потвърждение.'
    - ''
  update-available-confirmation:
  - ''
  - ' &eНалична е нова версия на nLogin{0} {1}'
  - ''
  - ' &6Искате ли да потвърдите актуализацията?'
  - ''
  update-available-restart:
  - ''
  - ' &eНалична е нова версия на nLogin{0} {1}'
  - ''
  - ' &6Рестартирайте сървъра си, за да приложите актуализацията.'
  - ''
  premium-fail:
  - ''
  - ' &c✖ &cВашият лиценз за &fnLogin v{0} &cне беше активиран успешно.'
  - '  &cОпитайте да изтеглите JAR отново от сайта:'
  - '  &b{1}'
  - ''
  - ' &c‼ &cАко проблемът продължава, препоръчваме да се свържете с разработчика.'
  - '  &7За да видите контактите, използвайте командата {2}'
  - ''
  premium-expired:
  - ''
  - ' &c✖ &cВашият лиценз за &fnLogin v{0} &cне беше активиран успешно.'
  - '  &cПодновете лиценза си чрез сайта: &b{1}'
  - ''
  premium-recommendation:
  - ''
  - ' &7Искате ли да направите влизането си практично?'
  - ' &7Вземете premium версията на nLogin сега'
  - ' &7и активирайте автоматично влизане за вашите потребители.'
  - ''
  - ' [&aКликнете тук за повече информация.]'
  - ''
  button:
    start-setup:
      text: '&a[✔ Стартиране на настройката]'
      hover: '&7Кликнете тук, за да стартирате настройката на plugin-а.'
    stable:
      text: '&a[Стабилна версия]'
      hover: |-
        &7&aСтабилният канал &7има по-малко грешки, но и по-малко функции.

        &6Препоръка: &fза сървъри, пуснати за публиката.
    latest:
      text: '&6[Най-нова версия]'
      hover: |-
        &7&6Каналът с най-новите версии &7съдържа най-актуалните версии.

        &6Препоръка: &fза сървъри, които искат най-новите функции
    automatic:
      text: '&a[Автоматични актуализации]'
      hover: '&7Няма да е необходимо потвърждение за актуализация.'
    manual:
      text: '&9[Ръчно потвърждение]'
      hover: '&7Ще трябва да потвърдите актуализацията с известие, подобно на това.'
    safer:
      text: '&a[По-безопасно]'
      hover: '&7Ще се използва по-сигурен алгоритъм за защита на паролите.'
    faster:
      text: '&c[По-бързо]'
      hover: '&7Ще се използва по-малко сигурен алгоритъм за защита на паролите.'
    pre-login:
      text: '&a[Показване преди]'
      hover: '&7Dialogs ще бъдат показани &aпреди влизане &7в сървъра.'
    after-login:
      text: '&9[Показване след]'
      hover: '&7Dialogs ще бъдат показани &9след влизане &7в сървъра.'
    install:
      text: '&a[⬇ Инсталиране]'
      hover: '&7Кликнете тук, за да инсталирате plugin-а автоматично.'
    skip:
      text: '&7[✖ Пропусни]'
      hover: null

title:
  setup:
    welcome-message-1:
      title: '&6Здравей, @player!'
      subtitle: '&eДобре дошли в nLogin!'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-2:
      title: ''
      subtitle: '&aМоля, прочетете предупреждението, преди да продължите.'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-3:
      title: ''
      subtitle: '&fКликнете бутона {0} &fза да продължите.'
      delays:
        fadeIn: 10
        stay: 80
        fadeOut: 10
  update-available:
    title: ''
    subtitle: '&aНалична е нова версия.'
    delays:
      fadeIn: 10
      stay: 80
      fadeOut: 10
