update:
  stable: '&aالإسطبل'
  latest: '&bالأخير'

notification:
  setup:
    select-language:
    - ''
    - ' &7لقد اكتشفنا أنك تستخدم اللغة &f{0}&7.'
    - ''
    - ' &6هل تريد استخدام هذه اللغة لـ nlogin؟'
    - ''
    - ' &c!! &eيؤثر هذا على لغة جميع اللاعبين!'
    - ''
    permission-required:
    - ''
    - ' &eلتكوين nlogin، تحتاج أن تصبح &cadministrator&e.'
    - ''
    - ' &6أضف الإذن &f"{0}"&6إلى ملحق الأذونات الخاص بك.'
    - ''
    - ' &c!! سيتم متابعة &eSetup بمجرد إضافة الإذن.'
    - ''
    welcome-message:
    - ''
    - ' &aشكراً جزيلاً لاختيار nlogin! :)'
    - ''
    - ' &6 لسلامتك، الرجاء قراءة الرسالة أدناه:'
    - '  &cعدم تحميل nlogin من مصادر غير معروفة أبداً.'
    - '  &cالنسخة المعدلة قد تحتوي على برامج خبيثة.'
    - ''
    - ' &aمصادر موثوقة:'
    - '  &7الموقع: &fnickuc.com'
    - '  &7GitHub: &fgithub.com/nickuc-com'
    - '  &7 تثبيت OpeNLogin (من &fSpigot &7 او &fGitHub&7)'
    - ''
    - ' &aالدعم الرسمي:'
    - '  &7الوثائق: &fdocs.nickuc.com/nlogin/'
    - '  &7الديسكور: &fnickuc.com/discord'
    - '  &7البريد الإلكتروني: &fsupport@nickuc.com'
    - ''
    configure-version-channel:
    - ''
    - ' &6اختر الإصدار المفضل.'
    - ''
    - ' &c!! &eيمكنك تغيير هذا لاحقًا عن طريق تشغيل &f{0}&e.'
    - ''
    configure-auto-or-manual-updates:
    - ''
    - ' &6اختر الطريقة المفضلة للتحديث.'
    - ''
    - ' &c!! &eيمكنك تغيير هذا لاحقًا عن طريق تشغيل &f{0}&e.'
    - ''
    configure-password-algorithm:
    - ''
    - ' &6حدد نوع التشفير المفضل لكلمات المرور.'
    - ''
    - ' &c!! &eيمكنك لاحقًا تغيير هذا الخيار يدويًا في &fconfig.yml&e.'
    - ''
    enable-dialogs:
    - ''
    - ' &6هل ترغب في استخدام القوائم (مربعات الحوار) كواجهة المصادقة؟'
    - ''
    - ' &eيستبدل مربعات الحوار المصادقة القائمة على الأوامر بقوائم قابلة للتخصيص.'
    - ''
    - ' &c!! &eهذه الميزة تعمل فقط للعملاء الذين يستخدمون 1.21.6 أو أكثر.'
    - ''
    configure-dialogs:
    - ''
    - ' &6اختر طريقتك المفضلة لإظهار مربعات الحوار.'
    - ''
    - ' &c!! &eيمكنك تغيير هذا الخيار يدوياً في &fconfig.yml&e.'
    - ''
    configure-bungeeguard:
    - ''
    - ' &6هل ترغب في تكوين BungeeGuard+ على الخادم؟'
    - ''
    - ' &c!! &eمن المستحسن تثبيت BungeeGuard+ في هذه الظروف:'
    - '  &8⋆ &e أنت تستخدم أي وكيل قائم على وكيل BungeeCord-Based.'
    - '  &8⋆ &e أنت تستخدم Velocity, لكن لا يمكنك إستخدام &"f"MODERN".'
    - ''
    - ' &c!! &eسوف تحتاج إلى تثبيت BungeeGuard+ JAR على جميع الخوادم.'
    - ''
    start-premium-configuration:
    - ''
    - ' تهانينا على شرائك &6⭐ nlogin Premium'
    - ''
    - ' &6 هذه هي الميزات الجديدة التي تم فتحها:'
    - ''
    - '&8⋆ &eتسجيل الدخول التلقائي &7 للمستخدمين مع ماينكرافت المتميزة.'
    - '&8⋆ &eالمصادقة &7 المزدوجة عن طريق الدسكورد والبريد الإلكتروني.'
    - ' &8⋆ &eجلسات تسجيل الدخول &7عند تسجيل الدخول بإستخدام عنوان IP.'
    - '  &8⋆ &e أعلى أولوية &مشاكل الدعم.'
    - '  &8⋆ &eعلامة &eالعملاء &7 في مجموعة ديسكورد.'
    - ''
    configure-username-appendix:
    - ''
    - ' &6هل ترغب في تمكين تذييل للاعبين المتميزين/غير المتصلين؟'
    - ''
    - ' &c!! &eللحصول على مزيد من المعلومات حول هذه الميزة، قم بزيارة: &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    configure-username-appendix-legacy-versions:
    - ''
    - ' &6 لا يمكن إضافة تذييل للاعبين المتميزين/غير المتصلين تلقائياً للإصدارات 1.18.2 أو أقل.'
    - ''
    - ' &eسوف تحتاج إلى تكوين شخصين مختلفين من عناوين IP يدوياً للاعبين المتميزين وغير المتصلين بالإنترنت.'
    - ''
    - ' &c!! &eللحصول على مزيد من المعلومات حول هذه الميزة، قم بزيارة: &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    enable-restrict-premium-nicknames:
    - ''
    - ' &6تقييد تسجيل اللاعبين غير المتصلين باستخدام الإسم المستعار المتميز؟ &e(للحسابات الجديدة)'
    - ''
    - ' &c!! اللاعبين &eOffline لن يتمكنوا من استخدام الإسم المستعار &fpremium (على سبيل المثال، Notch)&e، حتى إذا كان الإسم متوفر للتسجيل.'
    - ''
    enable-challenge-premium-nicknames:
    - ''
    - ' &6اكتشاف ما إذا كان اللاعبين يستخدمون حساب مميز؟ &e(باستخدام الاسم المستعار)'
    - ''
    - ' &c!! قد يتلقى &eOffline رسالة غير قابلة للتخصيص تقول &f"جلسة غير صالحة" &eعند تسجيل الدخول لأول مرة إلى الخادم.'
    - ''
    enable-premium-question:
    - ''
    - ' &6اكتشاف ما إذا كان اللاعبين يستخدمون حساب مميز؟ &e(باستخدام الاسم المستعار)'
    - ''
    - ' &c!! &eهذا الخيار ينصح به إذا كنت ترغب في التأكد من أن اللاعبين المتميزين يتلقون UUID.'
    - ''
    skip-premium-register:
    - ''
    - ' &6تخطي طلب تسجيل كلمة المرور ل &bاللاعبين المميزين&6؟'
    - ''
    - ' &c!! ينصح &eبتعطيل هذا الخيار إذا تم استخدام كلمة مرور اللاعبين في تكامل الويب (على سبيل المثال موقع الخادم).'
    - ''
    skip-bedrock-register:
    - ''
    - ' &6تخطي طلب تسجيل كلمة المرور لـ&bاللاعبين المميزين&6؟'
    - ''
    - ' &c!! ينصح &eبتعطيل هذا الخيار إذا تم استخدام كلمة مرور اللاعبين في تكامل الويب (على سبيل المثال موقع الخادم).'
    - ''
    nantibot-recommendation:
    - ''
    - ' &6نحن نوصي بتثبيت &fnAntiBot &6لمنع'
    - ' &6 خادمك من التعرض للهجوم بواسطة بوتات.'
    - ''
    - ' &c!! &eللحصول على مزيد من المعلومات حول هذه الإضافة، &6انقر هنا &e.'
    - ''
    nchat-recommendation:
    - ''
    - ' &6نوصي بتثبيت &fnChat&6،'
    - ' &6a إضافة دردشة تستبدل بشكل كامل "دردشة أسطورية".'
    - ''
    - ' &c!! &eللحصول على مزيد من المعلومات حول هذه الإضافة، &6انقر هنا &e.'
    - ''
    recommend-spawn-set:
    - ''
    - ' &6إحداثيات Player &cلا &6يجب حمايتها قبل تسجيل الدخول.'
    - ''
    - ' &c!! &eتعيين نقطة توليد آمنة باستخدام الأمر &f{0}&e.'
    - ''
    finish-configuration:
    - ''
    - ' &6 تأكيد للخروج من وضع الإعداد وحفظ جميع التغييرات.'
    - ''
    - ' &c!! &eسيتم قطع الاتصال بجميع اللاعبين عند التأكيد.'
    - ''
  update-available-confirmation:
  - ''
  - ' &eإصدار nlogin الجديد متاح{0} {1}'
  - ''
  - ' &6هل تريد تأكيد التحديث؟'
  - ''
  update-available-restart:
  - ''
  - ' &eإصدار nlogin الجديد متاح{0} {1}'
  - ''
  - ' &6أعد تشغيل الخادم الخاص بك لتطبيق التحديث.'
  - ''
  premium-fail:
  - ''
  - ' &c✖ رخصة &fnLogin v{0}&cالخاصة بك لم يتم تفعيلها بنجاح.'
  - '  &cحاول تحميل JAR مرة أخرى على الموقع:'
  - '  &b{1}'
  - ''
  - ' &c!! &cإذا استمرت المشكلة، فإننا نوصي بالاتصال بالمطور.'
  - '  &7 لقائمة جهات الاتصال، استخدم الأمر {2}'
  - ''
  premium-expired:
  - ''
  - ' &c✖ رخصة &fnLogin v{0}&cالخاصة بك لم يتم تفعيلها بنجاح.'
  - '  &cتجديد الترخيص الخاص بك من خلال الموقع: &b{1}'
  - ''
  premium-recommendation:
  - ''
  - ' &7تريد أن تجعل تسجيل الدخول الخاص بك عمليًا؟'
  - ' &7 احصل على النسخة المتميزة من nlogin الآن'
  - ' &7 وتفعيل تسجيل الدخول التلقائي للمستخدمين الخاص بك.'
  - ''
  - ' [&aانقر هنا لمزيد من المعلومات.]'
  - ''
  button:
    start-setup:
      text: '&a[✔ ابدأ الإعداد]'
      hover: '&7انقر هنا لبدء إعداد الإضافة.'
    stable:
      text: '&a[إصدار مستقر]'
      hover: |-
        &7 القناة &القابلة للتدوين &7لديها أخطاء أقل، ولكن لديها أيضا موارد أقل.

        &6نوصي بها: &fللخوادم التي تم إصدارها للجمهور.
    latest:
      text: '&6 [أحدث إصدار]'
      hover: |-
        &7 أحدث إصدار لـ &6قناة &7يحتوي على أحدث الإصدارات

        &6نوصي بها: &fللخوادم التي تريد أحدث الميزات
    automatic:
      text: '&a[تحديثات تلقائية]'
      hover: '&7لن تكون هناك حاجة لتأكيد التحديث.'
    manual:
      text: '&9[تأكيد يدوي]'
      hover: '&7سوف تحتاج إلى تأكيد التحديث بإشعار مشابه لهذا الإشعار.'
    safer:
      text: '&a[أكثر أمانًا]'
      hover: '&7سيتم استخدام خوارزمية أكثر أمنا لحماية كلمات المرور.'
    faster:
      text: '&c[أسرع]'
      hover: '&7سيتم استخدام خوارزمية أكثر أمنا لحماية كلمات المرور.'
    pre-login:
      text: '&a[إظهار السابق]'
      hover: '&7 سيتم عرض مربعات الحوار &aقبل دخول &7 الخادم.'
    after-login:
      text: '&9[إظهار بعد]'
      hover: '&7 سيتم عرض مربعات الحوار &aقبل دخول &7 الخادم.'
    install:
      text: '&a[⬇ تثبيت]'
      hover: '&7انقر هنا لتثبيت الإضافة تلقائياً.'
    skip:
      text: '&7[✖ تخطي]'
      hover: null

title:
  setup:
    welcome-message-1:
      title: '&6مرحبًا، @player!'
      subtitle: '&eمرحبا بك في nlogin!'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-2:
      title: ''
      subtitle: '&aالرجاء قراءة التحذير قبل المتابعة.'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-3:
      title: ''
      subtitle: '&fانقر فوق زر {0} &fللمتابعة.'
      delays:
        fadeIn: 10
        stay: 80
        fadeOut: 10
  update-available:
    title: ''
    subtitle: '&aإصدار جديد متوفر.'
    delays:
      fadeIn: 10
      stay: 80
      fadeOut: 10
