update:
  stable: '&aСтабільна'
  latest: '&bОстання'

notification:
  setup:
    select-language:
    - ''
    - ' &eМи виявили, що ви використовуєте &6{0} &eмову.'
    - ''
    - ' &6Бажаєте використовувати цю мову для nLogin?'
    - ''
    - ' &c!! &eЦе впливає на мову всіх гравців!'
    - ''
    permission-required:
    - ''
    - ' &eЩоб налаштувати nLogin, вам необхідно стати &cadministrator&e.'
    - ''
    - ' &6Додайте дозвіл &f"{0}" &6до вашого плагіну дозволів.'
    - ''
    - ' &c!! &eНалаштування продовжиться, як тільки добавиться дозвіл.'
    - ''
    welcome-message:
    - ''
    - ' &aДуже дякуємо вам за вибір nLogin! :)'
    - ''
    - ' &6Для вашої безпеки, будь ласка прочитайте повідомлення нижче:'
    - '  &cНіколи не завантажуйте nLogin з невідомих джерел.'
    - '  &cМодифікована версія може містити шкідливі програми.'
    - ''
    - ' &aНадійні джерела:'
    - '  &7Веб-сайт: &fnickuc.com'
    - '  &7GitHub: &fgithub.com/nickuc-com'
    - '  &7OpeNLogin інсталятор (від &fSpigot &7або &fGitHub&7)'
    - ''
    - ' &aОфіційна підтримка:'
    - '  &7Документація: &fdocs.nickuc.com/nlogin/'
    - '  &7Discord: &fnickuc.com/discord'
    - '  &7Email: &fsupport@nickuc.com'
    - ''
    configure-version-channel:
    - ''
    - ' &6Виберіть бажану версію каналу.'
    - ''
    - ' &c!! &eВи можете пізніше змінити це, запустивши &f{0}&e.'
    - ''
    configure-auto-or-manual-updates:
    - ''
    - ' &6Виберіть бажаний спосіб оновлення.'
    - ''
    - ' &c!! &eВи можете пізніше змінити це, запустивши &f{0}&e.'
    - ''
    configure-password-algorithm:
    - ''
    - ' &6Виберіть бажаний тип шифрування для паролів.'
    - ''
    - ' &c!! &eВи можете пізніше змінити цей параметр вручну в &fconfig.yml&e.'
    - ''
    enable-dialogs:
    - ''
    - ' &6Бажаєте використовувати меню (діалог), як інтерфейс автентифікації?'
    - ''
    - ' &eЦі діалогові вікна замінюють аутентифікацію за допомогою команд на настроювані меню.'
    - ''
    - ' &c!! &eЦя функція працює тільки для клієнтів, які використовують 1.21.6 або вище.'
    - ''
    configure-dialogs:
    - ''
    - ' &6Виберіть бажаний спосіб показу діалогів.'
    - ''
    - ' &c!! &eВи можете пізніше змінити цей параметр вручну в &fconfig.yml&e.'
    - ''
    configure-bungeeguard:
    - ''
    - ' &6Бажаєте налаштувати BungeeGuard+ на сервері?'
    - ''
    - ' &c!! &eЦе рекомендується встановлювати BungeeGuard+ в таких умовах:'
    - '  &8⋆ &eВи використовуєте проксі-сервер на базі BungeeCord.'
    - '  &8⋆ &eВи користуєтеся Velocity, але &f«MODERN» &eпереадресація недоступна.'
    - ''
    - ' &c‼ &eВам потрібно встановити BungeeGuard+ JAR на всіх серверах.'
    - ''
    start-premium-configuration:
    - ''
    - ' &aВітаємо з покупкою &6⭐ nLogin Premium'
    - ''
    - ' &6Ось нові розблоковані функції:'
    - ''
    - '  &8⋆ &eАвтоматичний вхід &7для гравців які мають преміум Minecraft.'
    - '  &8⋆ &eДвух-факторна &7аунтифікація за допомогою Discord та Email.'
    - '  &8⋆ &eЛогін сесії &7коли приєднано з IP адресою.'
    - '  &8⋆ &eВисокий преорітет&7в тех-підтримки.'
    - '  &8⋆ &eРоль покупця &7в Discord групі.'
    - ''
    configure-username-appendix:
    - ''
    - ' &6Бажаєте увімкнути appendix для преміум/офлайн гравців?'
    - ''
    - ' &c!! &eДля більшої інформації про цю функцію, відвідайте: &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    configure-username-appendix-legacy-versions:
    - ''
    - ' &6appendix для преміум / оффлайн гравців не можна додавати автоматично для версій 1.18.2 або ж нижче.'
    - ''
    - ' &eВам потрібно буде вручну налаштувати два різних IP для преміум і оффлайн гравців.'
    - ''
    - ' &c!! &eДля більшої інформації про цю функцію, відвідайте: &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    enable-restrict-premium-nicknames:
    - ''
    - ' &6Обмежити реєстрацію гравців в офлайн гравцях, використовуючи преміум нікнейми? &e(для нових акаунтів)'
    - ''
    - ' &c!! &eОфлайн гравці не зможуть використовувати &fліцензійні нікнейми (наприклад, Notch)&e, навіть якщо ім''я є доступним для реєстрації.'
    - ''
    enable-challenge-premium-nicknames:
    - ''
    - ' &6Виявити, чи гравці використовують преміум обліковий запис? &e(використовуючи нікнейм)'
    - ''
    - ' &c!! &eОфлайн гравці можуть отримувати повідомлення: &f"Недійсна сесія" &eна першого вхід на сервер.'
    - ''
    enable-premium-question:
    - ''
    - ' &6Виявити, чи гравці використовують преміум обліковий запис? &e(використовуючи інтерактивне питання в чаті)'
    - ''
    - ' &c!! &eЦей параметр рекомендується, якщо ви хочете переконатися, що гравці з ліцензією отримують Mojang UUID.'
    - ''
    skip-premium-register:
    - ''
    - ' &6Пропустити запит на реєстрацію пароля для &bпреміум гравців&6?'
    - ''
    - ' &c!! &eРекомендується вимкнути цю опцію, якщо пароль гравця використовується в веб-інтеграції (наприклад, на сайт сервера).'
    - ''
    skip-bedrock-register:
    - ''
    - ' &6Пропустити запит на реєстрацію пароля для &bBedrock гравців&6?'
    - ''
    - ' &c!! &eРекомендується вимкнути цю опцію, якщо пароль гравця використовується в веб-інтеграції (наприклад, на сайт сервера).'
    - ''
    nantibot-recommendation:
    - ''
    - ' &6Рекомендуємо встановити &fnAntiBot &6щоб'
    - ' &6Захисти від атаки ботів.'
    - ''
    - ' &c!! &eДля більшої інформації про цей плагін, &6натисти тут&e.'
    - ''
    nchat-recommendation:
    - ''
    - ' &6Ми рекомендуємо встановити &fnChat&6,'
    - ' &6чат плагій який повністю заміняє Legendchat.'
    - ''
    - ' &c!! &eДля більшої інформації про цей плагін, &6натисти тут&e.'
    - ''
    recommend-spawn-set:
    - ''
    - ' &6Координати гравця &cНЕ БУДУТЬ захищені перед входом.'
    - ''
    - ' &c!! &eУстановіть безпечну точку спавну використовуючи команду &f{0}&e.'
    - ''
    finish-configuration:
    - ''
    - ' &6Підтвердіть вихід з режиму налаштування та збереження всіх змін.'
    - ''
    - ' &c!! &eВсі гравці будуть відключені після підтвердження.'
    - ''
  update-available-confirmation:
  - ''
  - ' &eНова версія nLogin доступна{0} {1}'
  - ''
  - ' &6Бажаєте підтвердити оновлення?'
  - ''
  update-available-restart:
  - ''
  - ' &eНова версія nLogin доступна{0} {1}'
  - ''
  - ' &6Перезавантажте ваш сервер для застосування оновлення.'
  - ''
  premium-fail:
  - ''
  - ' &c✖ &cЛіцензію &fnLogin v{0} &cне вдалося успішно активувати.'
  - '  &cСпробуйте завантажити JAR ще раз на сайті:'
  - '  &b{1}'
  - ''
  - ' &c!! &cЯкщо проблема не зникне, ми рекомендуємо зв''язатися з розробником.'
  - '  &7Для списку контактів використовуйте команду {2}'
  - ''
  premium-expired:
  - ''
  - ' &c✖ &cЛіцензію &fnLogin v{0} &cне вдалося успішно активувати.'
  - '  &cПродовжіть вашу ліцензію на сайті: &b{1}'
  - ''
  premium-recommendation:
  - ''
  - ' &7Хочете зробити вхід більш зручнішим?'
  - ' &7Отримайте преміум-версію nLogin зараз'
  - ' &7Та увімкніть автоматичний вхід для ваших користувачів.'
  - ''
  - ' [&aНатисніть тут для отримання більш детальної інформації.]'
  - ''
  button:
    start-setup:
      text: '&a[✔ Початок налаштування]'
      hover: '&7Натисніть тут, щоб почати налаштування плагіна.'
    stable:
      text: '&a[Стабільна версія]'
      hover: |-
        &7&aСтабільний канал &7має менше помилок, але й менше ресурсів.

        &6Рекомендація: &fдля серверів, випущених у відкритий доступ.
    latest:
      text: '&6[Остання версія]'
      hover: |-
        &7У каналі &6«Останні версії» &7доступні найновіші версії.

        &6Рекомендація: &fдля серверів, які хочуть користуватися найновішими функціями
    automatic:
      text: '&a[Автоматичні оновлення]'
      hover: '&7Для оновлення підтвердження не потрібне.'
    manual:
      text: '&9[Ручне підтвердження]'
      hover: '&7Вам потрібно буде підтвердити оновлення зі сповіщенням, схожим на цей.'
    safer:
      text: '&a[Безпечніше]'
      hover: '&7Більш безпечний алгоритм буде використовуватися для захисту паролів.'
    faster:
      text: '&c[Бистріше]'
      hover: '&7Менш безпечний алгоритм буде використовуватися для захисту паролів.'
    pre-login:
      text: '&a[Показати до]'
      hover: '&7Діалогі будуть показані &aдо заходу &7на сервер.'
    after-login:
      text: '&9[Показати після]'
      hover: '&7Діалогі будуть показані &9після заходу &7на сервер.'
    install:
      text: '&a[⬇ Встановити]'
      hover: '&7Натисніть тут, щоб автоматично встановити плаґін.'
    skip:
      text: '&7[✖ Пропустити]'
      hover: null

title:
  setup:
    welcome-message-1:
      title: '&6Привіт, @player!'
      subtitle: '&eВітаємо в nLogin!'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-2:
      title: ''
      subtitle: '&aБудь ласка, прочитайте попередження перед продовженням.'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-3:
      title: ''
      subtitle: '&fНатисніть на кнопку {0} &f для продовження.'
      delays:
        fadeIn: 10
        stay: 80
        fadeOut: 10
  update-available:
    title: ''
    subtitle: '&aДоступна нова версія.'
    delays:
      fadeIn: 10
      stay: 80
      fadeOut: 10
