update:
  stable: '&aСтабильная'
  latest: '&bНовейшая'

notification:
  setup:
    select-language:
    - ''
    - ' &eМы обнаружили, что вы используете &6{0} &eязык.'
    - ''
    - ' &6Хотите ли вы использовать этот язык для nLogin?'
    - ''
    - ' &c!! &eЭто повлияет на язык для всех игроков!'
    - ''
    permission-required:
    - ''
    - ' &eДля настройки nLogin, вы должны быть &cадминистратором&e.'
    - ''
    - ' &6Добавить права &f"{0}" &6к вашему плагину на права.'
    - ''
    - ' &c!! &eУстановка будет продолжаться сразу после добавления права.'
    - ''
    welcome-message:
    - ''
    - ' &aБольшое спасибо за то, что выбрали nLogin! :)'
    - ''
    - ' &6Для вашей безопасности ознакомьтесь с сообщением ниже:'
    - '  &cНикогда не загружайте nLogin из неизвестных источников.'
    - '  &cИзмененная версия может содержать вредоносное ПО.'
    - ''
    - ' &aДоверенные источники:'
    - '  &7Сайт: &fnickuc.com'
    - '  &7GitHub: &fgithub.com/nickuc-com'
    - '  &7Установщик OpeNLogin (из &fSpigot &7или &fGitHub&7)'
    - ''
    - ' &aОфициальная поддержка:'
    - '  &7Документация: &fdocs.nickuc.com/nlogin/'
    - '  &7Discord: &fnickuc.com/discord'
    - '  &7E-mail: &fsupport@nickuc.com'
    - ''
    configure-version-channel:
    - ''
    - ' &6Выберите предпочтительный канал версий.'
    - ''
    - ' &c!! &eВы всегда можете изменить это, запустив &f{0}&e.'
    - ''
    configure-auto-or-manual-updates:
    - ''
    - ' &6Выберите предпочтительный метод обновления.'
    - ''
    - ' &c!! &eВы всегда можете изменить это, запустив &f{0}&e.'
    - ''
    configure-password-algorithm:
    - ''
    - ' &6Выберите предпочтительный тип шифрования паролей.'
    - ''
    - ' &c!! &eВы всегда можете изменить эту опцию вручную в &fconfig.yml&e.'
    - ''
    enable-dialogs:
    - ''
    - ' &6Вы хотите использовать меню (диалоговые окна) в качестве основного интерфейса?'
    - ''
    - ' &eДиалоги заменяют аутентификацию по командам, используя вместо них настраиваемые меню.'
    - ''
    - ' &c!! &eЭта функция работает только для пользователей с версией 1.21.6 или выше.'
    - ''
    configure-dialogs:
    - ''
    - ' &6Выберите предпочтительный способ отображения диалогов.'
    - ''
    - ' &c!! &eВы всегда можете изменить эту опцию вручную в &fconfig.yml&e.'
    - ''
    configure-bungeeguard:
    - ''
    - ' &6Хотите настроить BungeeGuard+ на сервере?'
    - ''
    - ' &c!! &eРекомендуется установить BungeeGuard+ при следующих обстоятельствах:'
    - '  &8* &eВы используете любой BungeeCord прокси.'
    - '  &8* &eВы используете velocity, но &f"MODERN forwarding" &eне может быть использован.'
    - ''
    - ' &c!! &eВам нужно будет установить BungeeGuard+ на все серверы.'
    - ''
    start-premium-configuration:
    - ''
    - ' &aПоздравляем с покупкой &6⭐ nLogin Premium'
    - ''
    - ' &6Новые разблокированные функции:'
    - ''
    - '  &8* &eАвтовход &7для пользователей с лицензией.'
    - '  &8* &eДвухэтапая аутентификация &7через Discord и Email.'
    - '  &8* &eСистема сеансов&7, не требующая пароль снова при входе с того же IP.'
    - '  &8* &eБолее высокий приоритет &7для поддержки.'
    - '  &8* &eТег покупателя &7в группе Discord.'
    - ''
    configure-username-appendix:
    - ''
    - ' &6Вы хотите включить приложение для лицензионных/пиратских игроков?'
    - ''
    - ' &c!! &eДля получения доп информации об этой функции есть &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    configure-username-appendix-legacy-versions:
    - ''
    - ' &6В версиях 1.18.2 и ниже нельзя добавить приложение автоматически.'
    - ''
    - ' &eВам необходимо вручную настроить два разных IP-адреса для игроков лицензии и пиратки.'
    - ''
    - ' &c!! &eДля получения доп информации об этой функции есть &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    enable-restrict-premium-nicknames:
    - ''
    - ' &6Ограничить регистрацию игроков в автономном режиме с помощью лицензии? &e(для новых аккаунтов)'
    - ''
    - ' &c!! &eИгроки пиратки не смогут использовать &fлицензионные ники(например, Notch)&e, даже если имя доступно для регистрации.'
    - ''
    enable-challenge-premium-nicknames:
    - ''
    - ' &6Определять, используют ли игроки лицензию? &e(используя ник)'
    - ''
    - ' &c!! &eИгроки, использующие пиратскую версию, могут увидеть не настраиваемое сообщение &f"Недопустимый сеанс" &eпри первом входе на сервер.'
    - ''
    enable-premium-question:
    - ''
    - ' &6Определять, используют ли игроки лицензию? &e(используя ник)'
    - ''
    - ' &c!! &eЭта опция рекомендуется, если вы хотите убедиться, чтобы лицензионные игроки с Mojang UUID.'
    - ''
    skip-premium-register:
    - ''
    - ' &6Пропустить запрос на регистрацию пароля для &bигроков с лицензией&6?'
    - ''
    - ' &c!! Рекомендуется отключить эту опцию, если пароль игроков используется в веб-интеграции (например, сайт сервера).'
    - ''
    skip-bedrock-register:
    - ''
    - ' &6Пропустить запрос на регистрацию пароля для &bигроков с лицензией&6?'
    - ''
    - ' &c!! Рекомендуется отключить эту опцию, если пароль игроков используется в веб-интеграции (например, сайт сервера).'
    - ''
    nantibot-recommendation:
    - ''
    - ' &6Мы рекомендуем установить &fnAntiBot'
    - ' &6для предотвращения бот атак.'
    - ''
    - ' &c!! &eДля получения дополнительной информации об этом плагине, &6нажмите здесь&e.'
    - ''
    nchat-recommendation:
    - ''
    - ' &6Мы рекомендуем установить &fчат плагин&6,'
    - ' &6который полностью заменяет Legendchat.'
    - ''
    - ' &c!! &eДля получения дополнительной информации об этом плагине, &6нажмите здесь&e.'
    - ''
    recommend-spawn-set:
    - ''
    - ' &6Координаты &cНЕ ЗАЩИЩЕНЫ &6во время логина.'
    - ''
    - ' &c!! &eЗадайте безопасную точку спавна с помощью команды &f{0}&e.'
    - ''
    finish-configuration:
    - ''
    - ' &6Подтвердите выход из режима настройки и сохранения всех изменений.'
    - ''
    - ' &c!! &eВсе игроки будут отключены после подтверждения.'
    - ''
  update-available-confirmation:
  - ''
  - ' &eДоступна новая версия nLogin{0} {1}'
  - ''
  - ' &6Вы хотите подтвердить обновление?'
  - ''
  update-available-restart:
  - ''
  - ' &eДоступна новая версия nLogin{0} {1}'
  - ''
  - ' &6Перезагрузите сервер для применения обновления.'
  - ''
  premium-fail:
  - ''
  - ' &c✖ &cВаша &cлицензия &fnLogin v{0} не активировалась.'
  - '  &cПопробуйте снова загрузить JAR на сайте:'
  - '  &b{1}'
  - ''
  - ' &c!! Если проблема не устранена, мы рекомендуем связаться с разработчиком.'
  - '  &7Для списка контактов, используйте команду {2}'
  - ''
  premium-expired:
  - ''
  - ' &c✖ &cВаша &cлицензия &fnLogin v{0} не активировалась.'
  - '  &cОбновить лицензию можно через сайт: &b{1}'
  - ''
  premium-recommendation:
  - ''
  - ' &7Хотите сделать свой логин практичней?'
  - ' &7Получить премиум-версию nLogin сейчас'
  - ' &7 и включите автоматический вход для ваших пользователей.'
  - ''
  - ' [&aНажмите здесь для получения дополнительной информации.]'
  - ''
  button:
    start-setup:
      text: '&a[✔ Начать установку]'
      hover: '&7Нажмите здесь, чтобы начать установку плагина.'
    stable:
      text: '&a[Стабильная версия]'
      hover: |-
        &7У канала &7меньше ошибок, но также меньше ресурсов.

        &6Рекомендация: &fдля серверов, публичных серверов.
    latest:
      text: '&6[Новейшая версия]'
      hover: |-
        &7Новейшая версия &7может содержать баги.

        &6Рекомендация: &fдля серверов, которым нужны последние функции
    automatic:
      text: '&a[Автоматическое обновление]'
      hover: '&7Для обновления больше не потребуются подтверждения.'
    manual:
      text: '&9[Ручное подтверждение]'
      hover: '&7Вам нужно будет подтвердить обновление через уведомление, аналогичное этому.'
    safer:
      text: '&а[Безопаснее]'
      hover: '&7Для защиты паролей будет использоваться более безопасный алгоритм.'
    faster:
      text: '&c[Быстрее]'
      hover: '&7Для защиты паролей будет использоваться менее безопасный, но более производительный алгоритм.'
    pre-login:
      text: '&a[Показать до]'
      hover: '&7Перед входом на &7сервер будут показаны диалоги.'
    after-login:
      text: '&9[Показать позже]'
      hover: '&7Перед входом на &7сервер будут показаны диалоги.'
    install:
      text: '&a[⬇ Установить]'
      hover: '&7Нажмите здесь, чтобы автоматически установить плагин.'
    skip:
      text: '&7[✖ пропустить]'
      hover: null

title:
  setup:
    welcome-message-1:
      title: '&6Привет, @player!'
      subtitle: '&eДобро пожаловать в nLogin!'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-2:
      title: ''
      subtitle: '&aПожалуйста, прочитайте предупреждение перед продолжением.'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-3:
      title: ''
      subtitle: '&fНажмите на кнопку {0} &fдля продолжения.'
      delays:
        fadeIn: 10
        stay: 80
        fadeOut: 10
  update-available:
    title: ''
    subtitle: '&aДоступна новая версия.'
    delays:
      fadeIn: 10
      stay: 80
      fadeOut: 10
