update:
  stable: '&a安定版'
  latest: '&b最新版'

notification:
  setup:
    select-language:
    - ''
    - ' &eあなたが &6{0} &e言語を使用していることを検知しました。'
    - ''
    - ' &6nLoginでこの言語を使用しますか？'
    - ''
    - ' &c‼ &eこれは全プレイヤーの言語に影響します！'
    - ''
    permission-required:
    - ''
    - ' &enLoginを設定するには、&c管理者&eになる必要があります。'
    - ''
    - ' &6権限プラグインに権限 &f"{0}" &6を追加してください。'
    - ''
    - ' &c‼ &e権限が追加され次第、セットアップが続行されます。'
    - ''
    welcome-message:
    - ''
    - ' &anLoginを選んでいただき、ありがとうございます！ :)'
    - ''
    - ' &6安全のために、以下のメッセージをお読みください：'
    - '  &c未知のソースからnLoginをダウンロードしないでください。'
    - '  &c改造されたバージョンには悪意のあるソフトウェアが含まれている可能性があります。'
    - ''
    - ' &a信頼できるソース：'
    - '  &7ウェブサイト: &fnickuc.com'
    - '  &7GitHub: &fgithub.com/nickuc-com'
    - '  &7OpeNLoginインストーラー (&fSpigot &7または &fGitHub&7 から)'
    - ''
    - ' &a公式サポート：'
    - '  &7ドキュメント: &fdocs.nickuc.com/nlogin/'
    - '  &7Discord: &fnickuc.com/discord'
    - '  &7メール: &fsupport@nickuc.com'
    - ''
    configure-version-channel:
    - ''
    - ' &6希望するバージョンチャンネルを選択してください。'
    - ''
    - ' &c‼ &eこれは後で &f{0} &eを実行して変更できます。'
    - ''
    configure-auto-or-manual-updates:
    - ''
    - ' &6希望するアップデート方法を選択してください。'
    - ''
    - ' &c‼ &eこれは後で &f{0} &eを実行して変更できます。'
    - ''
    configure-password-algorithm:
    - ''
    - ' &6パスワードの希望する暗号化タイプを選択してください。'
    - ''
    - ' &c‼ &eこのオプションは後で &fconfig.yml &eで手動で変更できます。'
    - ''
    enable-dialogs:
    - ''
    - ' &6認証UIとしてメニュー（ダイアログ）を使用しますか？'
    - ''
    - ' &eダイアログは、コマンドベースの認証をカスタマイズ可能なメニューに置き換えます。'
    - ''
    - ' &c‼ &eこの機能は1.21.6以上のクライアントでのみ動作します。'
    - ''
    configure-dialogs:
    - ''
    - ' &6ダイアログの希望する表示方法を選択してください。'
    - ''
    - ' &c‼ &eこのオプションは &fconfig.yml &eで手動で変更できます。'
    - ''
    configure-bungeeguard:
    - ''
    - ' &6サーバーでBungeeGuard+を設定しますか？'
    - ''
    - ' &c‼ &e以下の場合、BungeeGuard+をインストールすることをお勧めします：'
    - '  &8⋆ &eBungeeCordベースのプロキシを使用している場合。'
    - '  &8⋆ &eVelocityを使用しているが、&f"MODERN" &e転送が使用できない場合。'
    - ''
    - ' &c‼ &eすべてのサーバーにBungeeGuard+のJARをインストールする必要があります。'
    - ''
    start-premium-configuration:
    - ''
    - ' &a&6⭐ nLogin Premium&aの購入おめでとうございます'
    - ''
    - ' &6以下の新しい機能がアンロックされました：'
    - ''
    - ' &8⋆ &7プレミアム版Minecraftユーザーの&e自動ログイン&7。'
    - ' &8⋆ &7Discordとメールによる&e2段階認証&7。'
    - ' &8⋆ &7IPアドレスでログインする際の&eログインセッション&7。'
    - ' &8⋆ &7サポート対応の&e優先順位向上&7。'
    - '  &8⋆ &7Discordグループでの&eカスタマータグ&7。'
    - ''
    configure-username-appendix:
    - ''
    - '&6プレミアム/オフラインプレイヤー向けの付加文字(appendix)を有効にしますか？'
    - ''
    - ' &c‼ &eこの機能の詳細については、以下をご覧ください: &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    configure-username-appendix-legacy-versions:
    - ''
    - '&6バージョン1.18.2以下では、プレミアム/オフラインプレイヤー向けの付加文字(appendix)を自動的に追加することはできません。'
    - ''
    - ' &eプレミアムプレイヤーとオフラインプレイヤー用に2つの異なるIPを手動で設定する必要があります。'
    - ''
    - ' &c‼ &eこの機能の詳細については、以下をご覧ください: &bdocs.nickuc.com/nlogin/username-appender'
    - ''
    enable-restrict-premium-nicknames:
    - ''
    - ' &6オフラインプレイヤーがプレミアムプレイヤーの名前で登録するのを制限しますか？ &e(新規アカウント向け)'
    - ''
    - ' &c‼ &eオフラインプレイヤーは、登録可能な名前であっても&fプレミアムネーム（例：Notch）&eを使用できなくなります。'
    - ''
    enable-challenge-premium-nicknames:
    - ''
    - ' &6プレイヤーがプレミアムアカウントを使用しているか検出しますか？ &e(ニックネームを使用)'
    - ''
    - ' &c‼ &eオフラインプレイヤーが初めてサーバーにログインする際、カスタマイズできない &f"Invalid session" &eというメッセージを受け取る場合があります。'
    - ''
    enable-premium-question:
    - ''
    - ' &6プレイヤーがプレミアムアカウントを使用しているか検出しますか？ &e(対話型の質問を使用)'
    - ''
    - ' &c‼ &eプレミアムプレイヤーが確実にMojangのUUIDを受け取れるようにしたい場合は、このオプションをお勧めします。'
    - ''
    skip-premium-register:
    - ''
    - ' &bプレミアムプレイヤー&6のパスワード登録の要求をスキップしますか？'
    - ''
    - ' &c‼ &eプレイヤーのパスワードをウェブ連携（サーバーのウェブサイトなど）で使用する場合、このオプションを無効にすることをお勧めします。'
    - ''
    skip-bedrock-register:
    - ''
    - ' &cBedrockプレイヤー&6のパスワード登録の要求をスキップしますか？'
    - ''
    - ' &c‼ &eプレイヤーのパスワードをウェブ連携（サーバーのウェブサイトなど）で使用する場合、このオプションを無効にすることをお勧めします。'
    - ''
    nantibot-recommendation:
    - ''
    - ' &6サーバーがボットから攻撃されるのを防ぐために、'
    - ' &fnAntiBot &6のインストールをお勧めします。'
    - ''
    - ' &c‼ &eこのプラグインの詳細については、&6ここをクリック&eしてください。'
    - ''
    nchat-recommendation:
    - ''
    - ' &6Legendchatを完全に置き換えるチャットプラグイン、'
    - ' &fnChat &6のインストールをお勧めします。'
    - ''
    - ' &c‼ &eこのプラグインの詳細については、&6ここをクリック&eしてください。'
    - ''
    recommend-spawn-set:
    - ''
    - ' &6ログイン前、プレイヤーの座標は&c保護されません&6。'
    - ''
    - ' &c‼ &eコマンド &f{0} &eを使用して、安全なスポーン地点を設定してください。'
    - ''
    finish-configuration:
    - ''
    - ' &6セットアップモードを終了し、すべての変更を保存することを確認してください。'
    - ''
    - ' &c‼ &e確認後、すべてのプレイヤーが切断されます。'
    - ''
  update-available-confirmation:
  - ''
  - ' &e新しいnLoginバージョンが利用可能です{0} {1}'
  - ''
  - ' &6アップデートを確定しますか？'
  - ''
  update-available-restart:
  - ''
  - ' &e新しいnLoginバージョンが利用可能です{0} {1}'
  - ''
  - ' &6アップデートを適用するには、サーバーを再起動してください。'
  - ''
  premium-fail:
  - ''
  - ' &c✖ &fnLogin v{0} &cのライセンスが正常にアクティベートされませんでした。'
  - '  &cウェブサイトでJARを再度ダウンロードしてみてください：'
  - '  &b{1}'
  - ''
  - ' &c‼ &c問題が解決しない場合は、開発者に連絡することをお勧めします。'
  - '  &7連絡先を表示するには、コマンド {2} を使用してください'
  - ''
  premium-expired:
  - ''
  - ' &c✖ &fnLogin v{0} &cのライセンスが正常にアクティベートされませんでした。'
  - '  &cサイトからライセンスを更新してください: &b{1}'
  - ''
  premium-recommendation:
  - ''
  - ' &7ログインをより実用的にしたいですか？'
  - ' &7今すぐnLoginのプレミアム版を入手して、'
  - ' &7ユーザー向けの自動ログインを有効にしましょう。'
  - ''
  - ' [&a詳細についてはここをクリックしてください。]'
  - ''
  button:
    start-setup:
      text: '&a[✔ セットアップ開始]'
      hover: '&7プラグインのセットアップを開始するにはここをクリックしてください。'
    stable:
      text: '&a[安定版]'
      hover: |-
        &7&a安定版チャンネル&7はバグが少ないですが、新機能も少なくなります。

        &6推奨: &f一般公開されているサーバー向け。
    latest:
      text: '&6[最新版]'
      hover: |-
        &7&6最新版チャンネル&7は常に最新のバージョンを提供します。

        &6推奨: &f最新機能を求めるサーバー向け。
    automatic:
      text: '&a[自動アップデート]'
      hover: '&7アップデート時の確認が不要になります。'
    manual:
      text: '&9[手動確認]'
      hover: '&7このような通知からアップデートを手動で確認する必要があります。'
    safer:
      text: '&a[より安全]'
      hover: '&7パスワード保護のため、より安全なアルゴリズムが使用されます。'
    faster:
      text: '&c[より高速]'
      hover: '&7パスワード保護のため、比較的安全性の低いアルゴリズムが使用されます。'
    pre-login:
      text: '&a[ログイン前に表示]'
      hover: '&7ダイアログはサーバーに&a入る前に&7表示されます。'
    after-login:
      text: '&9[ログイン後に表示]'
      hover: '&7ダイアログはサーバーに&9入った後に&7表示されます。'
    install:
      text: '&a[⬇ インストール]'
      hover: '&7プラグインを自動インストールするにはここをクリックしてください。'
    skip:
      text: '&7[✖ スキップ]'
      hover: null

title:
  setup:
    welcome-message-1:
      title: '&6こんにちは、@playerさん！'
      subtitle: '&enLoginへようこそ！'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-2:
      title: ''
      subtitle: '&a続行する前に警告をお読みください。'
      delays:
        fadeIn: 10
        stay: 60
        fadeOut: 10
    welcome-message-3:
      title: ''
      subtitle: '&f続行するには {0} &fボタンをクリックしてください。'
      delays:
        fadeIn: 10
        stay: 80
        fadeOut: 10
  update-available:
    title: ''
    subtitle: '&a新しいバージョンが利用可能です。'
    delays:
      fadeIn: 10
      stay: 80
      fadeOut: 10
