####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                          __             _                                    | #
# |                                 _ __   / /  ___   __ _(_)_ __                                | #
# |                                | '_ \ / /  / _ \ / _` | | '_ \                               | #
# |                                | | | / /__| (_) | (_| | | | | |                              | #
# |                                |_| |_\____/\___/ \__, |_|_| |_|                              | #
# |                                                    |___/                                     | #
# |                                                                                              | #
# |                      A practical, secure and friendly authentication plugin                  | #
# |                                                                                              | #
# |                                © 2026 - Powered by nickuc.com                                | #
# |                                                                                              | #
# |              List of translation authors: https://crowdin.com/project/nlogin/members         | #
# |                                                                                              | #
# |  New options are not automatically added in this file. Default values are used               | #
# |  if an option is not found.                                                                  | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

pending:
  login: '&fВикористовуйте: &7/&6login <пароль>'
  register: '&fВикористовуйте: &7/&6register <пароль> <повтор пароля>'
  action-bar:
    singular: '&cВи маєте {0} секунд щоб {login///register}.'
    plural: '&cВи маєте {0} секунд щоб {login///register}.'

success:
  login: '&aВи успішно авторизувалися.'
  register: '&fВи &cвже &fзареєстровані!'
  session: '&eВаш сеанс входу продовжено.'
  premium: '&eВи успішно авторизувались за допомогою &aліцензії.'
  bedrock: '&eВи успішно авторизувались за допомогою &aBedrock.'
  change-password: '&aВаш пароль був успішно змінений.'
  reload: '&eПлагін успішно перезавантажений.'
  kick:
    unregister: '&aВаш обліковий запис успішно видалений.'
    marked-offline: '&7Ваш акаунт позначено як &6офлайн&7, будь ласка, перепідключіться.'
    challenge-premium: '&7Щоб підтвердити, що ви використовуєте &6ліцензію&7, будь ласка, увійдіть на сервер ще раз.'

error:
  not-registered: '&cЦе ім''я ще не зареєстровано.'
  offline: '&cЦей гравець офлайн.'
  address-limit: '&cВи вичерпали обмеження облікових записів на IP.'
  database: '&cНа жаль, нам не вдалося завершити цю операцію. Будь ласка спробуйте ще раз. [SQL FAIL]'
  command:
    usage: '&cВикористання: {0}.'
    no-permission: '&cУ Вас немає прав на використання цієї команди.'
    player-required: '&cВи маєте бути гравцем, щоб використовувати цю команду.'
    console-required: '&cЦю команду можна використовувати тільки з консолі.'
    account-collision:
    - '&fЗнайдено кілька облікових записів із нікнеймом &a{0}&f:'
    - '&8⋆ &7{1} {2}'
    - ''
    - '&c‼ &eВиконайте команду ще раз, переконайтеся що ви використовуйте нікнейм, що відповідає потрібному типу облікового запису.'
    arguments:
      password: пароль
      current-password: поточний пароль
      new-password: новий пароль
  already:
    login: '&cВи вже авторизовані.'
    login-other: '&cЦей гравець уже авторизований.'
    registered: '&cЦе ім''я уже зареєстровано.'
    premium: '&fВаш аккаунт вже відзначений як &6ліцензійний.'
  password:
    same-as-current: '&cВведений пароль такий же, як теперішній.'
    too-large: '&cВведений пароль дуже великий.'
    too-small: '&cВведений пароль дуже малий.'
    not-secure: '&cВведений пароль не відповідає вимогам безпеки. Будь ласка, додайте цифру, великі та малі літери та спеціальний символ.'
    do-not-match: '&cПаролі не співпадають.'
    require-confirmation: '&cВи маєте підтвердити пароль.'
    incorrect: '&cНевірний пароль, спробуйте ще раз.'
  kick:
    incorrect-password: '&cВи ввели невірний пароль'
    wait-server-start: |-
      &cСервер ще не запустився повністю.
      &cПочекайте, перед тим як зайти.
    account-blocked: |-
      &cВашу адресу заблоковано через ймовірне вторгнення.&r
      &r&cБан буде знято через: {0}
    account-unregistered: |-
      &cЦей сервер не приймає нових акаунтів для реєстрації.

      &cДля отримання додаткової інформації зверніться до адміністрації сервера.
    invalid-nickname: '&cВаше ім''я невірне. Приберіть пробіли та недійсні символи з Вашого імені.'
    bedrock-nickname: '&cОбраний префікс ніку &f("{0}") &fце доступний лише гравцям &cBedrock.'
    bedrock-unlinked: |-
      &cВибраний нікнейм &f("{0}") &cзарезервовано за ліцензійним гравцем Java.

      &eЩоб отримати доступ до цього облікового запису, зв'яжіть свій Java-профіль із профілем Bedrock за допомогою команди &f/linkaccount&e.
    transferred-nickname: |-
      &cВибране ім'я &f("{0}") &cбуло зарезервовано та передано до акаунту з таким самим UUID.

      &eЩоб увійти, будь ласка, використовуйте інший нікнейм.
    already-online: '&cЦей гравець вже онлайн.'
    unknown-hostname: |-
      &4[nLogin] Ім’я хоста, яке використовується &f({0}) &4, не було визначено в конфігурації.
      &r
      &r&cЯкщо це дійсна IP-адреса, додайте її до найбільш відповідної категорії в розділі конфігурації &f"premium.username-appender"&c.
      &r
      &r&eДля отримання додаткової інформації перегляньте підручник із додавання імені користувача:
      &r&bhttps://docs.nickuc.com/nlogin/username-appender
    premium-not-logged: |-
      &7Ім'я користувача &6{0} &7пов'язане з підтвердженим &aпреміум-акаунтом&7, але термін дії вашої сесії &cзакінчився&7.

      &eЯкщо ви є власником цього облікового запису, перезапустіть Minecraft і увійдіть знову.
    premium-challenge: |-
      &eПід час останньої спроби входу, нам не вдалося автентифікувати ваш обліковий запис.

      &fЯкщо ви використовуєте &aліцензійний &fакаунт, перезапустіть Minecraft і увійдіть знову.

      &fЯкщо ваш акаунт &coffline&f, будь ласка, увійдіть знову, щоб завершити перевірку.
    timeout:
      login: '&fВи &cдуже довго &fавторизувались.'
      register: '&fВи &cдуже довго &fреєструвались.'

notification:
  all-viewed: '&aУсі сповіщення переглянуто.'
  premium-question:
  - ''
  - ' &eВи використовуєте ліцензію?'
  - ' &7(&fпісля прийняття вам потрібно буде повторно підключитися до сервера&f).'
  - ''
  premium-transfer-question:
  - ''
  - ' &eОфлайн аккаунт вже зареєстровано з цим нікнеймом &f@player&e.'
  - ''
  - ' &6Бажаєте перести дані з цього аккаунта або створити новий аккаунт?'
  - ''
  - ' &c‼ &eВам потрібно пройти автентифікацію, щоб підтвердити власництво облікового запису.'
  - ''
  premium-transfer-confirmation:
  - ''
  - ' &6Бажаєте підтвердити перенесення даних із &f@player &6на ваш ліцензійний аккаунт?'
  - ''
  - ' &c!!&eПісля підтвердження перенесення, ви будете відключенні від сервера.'
  - ''
  password-update:
  - ''
  - ' &eВаш пароль потребує оновлення.'
  - ''
  - ' &7Будь ласка, змініть пароль за допомогою команди нижче:'
  - ' &f/changepass <поточний пароль> <новий пароль>'
  - ''
  button:
    confirm-read:
      text: '&a[✔ Позначити як прочитане]'
      hover: null
    yes-btn:
      text: '&a[✔ Так]'
      hover: null
    no-btn:
      text: '&c[✖ Ні]'
      hover: null
    new-account:
      text: '&a[Новий акаунт]'
      hover: null
    transfer-data:
      text: '&9[Перенести дані]'
      hover: null

2fa:
  not-registered: '&fУ вас &cнемає &fаккаунта &6{0}.'
  already-registered: '&fВи &cвже&f зареєстрували свій &6{0}.'
  register-limit: '&cВи вичерпали ліміт облікових записів з однаковими {0}.'
  unregistered: '&eВаш {0} успішно розреєстровано.'
  incorrect-code: '&cНевірний код, спробуйте ще раз.'
  rate-limit: '&cЛіміт вичерпано. Почекайте {0} хвилин та спробуйте ще раз.'
  confirmed-account: '&aВаш акаунт {0} успішно зареєстровано.'
  confirmation-message-sent: |-
    &fКод підтвердження було надіслано на ваш &6&6{0}&7.
    &8(&f{1}&8).
  command-delay: '&fЗачекайте деякий час, перш ніж знову виконувати цю команду.'
  help-command:
  - ''
  - ' &fСтатус: [&6{2} підключений//&c{2} не підключений]&f.'
  - ''
  - ' [&8⋆ &7/&6{0} add &7- &fПрив''язати {1}]'
  - ' [&8⋆ &7/&6{0} remove &7- &fВідв''язати {1}]'
  - ' [&8⋆ &7/&6{0} recover &7- &fВідновити аккаунт]'
  - ' [&8⋆ &7/&6{0} 2fa &7- &fУвімкнути/Вимкнути 2FA]'
  - ''
  recover-command:
  - ''
  - ' &eВиберіть спосіб відновлення:'
  - ' [&8⋆ &7{0}: &f/{1} recover]'
  - ''
  switch:
    enabled: '&f2FA &2активовано&f.'
    disabled: '&f2FA &cвимкнено&f.'
  recover:
    not-equal: '&fДаний &e{0}&f не збігається з зареєстрованим.'
    message-sent: '&fНа ваш &6прив''язаний акаунт&f було надіслано повідомлення про відновлення.'
    change-password: '&fВаш пароль було автоматично змінено на &e''{0}''&f.'
  discord:
    account-linked: |-
      &aВітаємо, ваш аккаунт успішно прив'язаний.
      &fВи прив'язалися до &6{0}&f.
    confirm-account:
    - ''
    - ' &fДля завершення, вам потрібно підтвердити &aДіскорд-акаунт&f.'
    - ' &7Приєднайтеся до &b{0} &7та введіть'
    - ' &7Напишіть нашому боту: &e{1}'
    - ''
    - ' [&2Натисніть сюди&f, щоб отримати команду.]'
    - ''
    warn-message:
    - ''
    - ' &6Система безпеки Discord'
    - ' &7Виконайте команду &f/discord add &7, щоб прив''язати'
    - ' &fЗ прив''язкою до &aDiscord&f, ви максимально захистите свій обліковий запис.'
    - ''
    discord-required:
    - ''
    - ' &7Поточний сервер вимагає пов’язати обліковий'
    - ' &aзапис Discord, &7щоб завершити реєстрацію.'
    - ''
    - ' &6Будь ласка, введіть &f/discord add&6.'
    - ''
    address-changed:
    - ''
    - ' &7Вам потрібно підтвердити вхід в обліковий запис.'
    - ' &7Повідомлення безпеки надіслано на ваш зареєстрований Discord.'
    - ''
    - ' &aНатисніть кнопку повідомлення, щоб підтвердити свою особу.'
    - ''
    dm:
      configure:
        too-recent:
          title: Занадто новий акаунт
          description: Ви не можете прив'язати свій Discord, оскільки ваш акаунт створено занадто недавно.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
        invalid:
          title: Невірний код
          description: Вибачте, але введений токен недійсний або не існує.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
        success:
          title: Discord пов’язано
          description: Ваш Discord успішно підключено.
          image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
          color: '#808080'
      verify:
        title: Підтвердьте автентифікацію свого облікового запису.
        description: |-
          Для доступу до облікового запису @player потрібне підтвердження автентифікації.

          Якщо це були не ви, забороніть операцію та негайно змініть пароль.
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
        allow: Дозволити
        deny: Відхилити
      recover:
        title: Запит на відновлення пароля.
        description: |-
          З вашого облікового запису @player надійшов запит на відновлення пароля.

          Якщо це були не ви, забороніть операцію та негайно змініть пароль.
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
        allow: Дозволити
        deny: Відхилити
      new-password:
        title: Новий пароль для @player
        description: |-
          Для вашого акаунту згенеровано новий пароль:
          `{0}`
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
      password-changed:
        title: Пароль змінено для @player
        description: |-
          Ваш пароль змінено на:
          `{0}`
        image: https://www.nickuc.com/static/assets/img/2fa-lock-default.png
        color: '#808080'
  email:
    invalid-email: '&cВведено невірну пошту.'
    not-allowed: '&cДомен обраної електронної пошти не дозволений.'
    server-email: '&cВи не можете використовувати адресу пошти сервера.'
    warn-message:
    - ''
    - ' &aСистема безпеки email'
    - ' &aВикористовуйте команду &f/email associate <ваш email> &aщоб покращити вашу безпеку.'
    - ' &aЗ прив''язкою до email, ви уникнете злому свого облікового запису.'
    - ''
    email-required:
    - ''
    - ' &7Поточний сервер вимагає пов’язати дійсну електронну'
    - ' &aелектронну адресу, &7щоб завершити реєстрацію.'
    - ''
    - ' &6Будь ласка, введіть &f/email add <ваш email>&6.'
    - ''
    address-changed:
    - ''
    - ' &7Вам потрібно підтвердити вхід в обліковий запис.'
    - ' &7На вашу зареєстровану електронну адресу надіслано повідомлення безпеки.'
    - ''
    - ' &aВикористовуйте команду §f/email <код>, &aщоб завершити автентифікацію.'
    - ''
    smtp:
      configure:
        subject: Підтвердження облікового запису @player
        content:
        - <h1>
        - ' Доброго дня, @player!'
        - </h1>
        - <p>
        - ' Щоб завершити процес реєстрації email, використовуйте команду <strong>"/email @code"</strong>.'
        - </p>
        - <p>
        - ' Якщо це були не Ви, проігноруйте цей лист.'
        - </p>
      verify:
        subject: Підтвердження входу до облікового запису @player
        content:
        - <h1>
        - ' Доброго дня, @player!'
        - </h1>
        - <p>
        - ' Щоб авторизуватися на сервері, використовуйте команду <strong>"/email @code"</strong>.'
        - </p>
        - <p>
        - ' Якщо це були не ви, змініть пароль <strong>НЕГАЙНО</strong>.'
        - </p>
      recover:
        subject: Відновлення акаунту @player
        content:
        - <h1>
        - ' Вітаю, @player!'
        - </h1>
        - <p>
        - ' Для відновлення облікового запису скористайтесь командою <strong>"/email <новий пароль> @code"</strong>.'
        - </p>
        - <p>
        - ' Якщо це були не Ви, проігноруйте цей лист.'
        - </p>
      new-password:
        subject: Новий пароль для @player
        content:
        - <h1>
        - ' Привіт, @player!'
        - </h1>
        - <p>
        - ' Для вашого акаунту згенеровано новий пароль: {0}'
        - </p>
      password-changed:
        subject: Пароль змінено для @player
        content:
        - <h1>
        - ' Привіт, @player!'
        - </h1>
        - <p>
        - ' Ваш пароль змінено на: {0}'
        - </p>

bedrock:
  forms:
    login:
      title: Авторизація
      content:
      - Вітаю, @player!
      - 'Для входу на сервер введіть ваш пароль нижче:'
      - ''
      - '[Пароль//Введіть ваш пароль]'
      - ''
    register:
      title: Реєстрація
      content:
      - Вітаю, @player!
      - Для гри на сервері потрібно зареєструватися.
      - Будь ласка, введіть свій пароль нижче.
      - ''
      - '[Пароль//Введіть ваш пароль]'
      - '[Підтвердження//Введіть ваш пароль ще раз]'
      - ''

dialogs:
  login:
    title: '&#ffdb60Ведіть ваш пароль'
    body:
    - '&6Вітаю, &f@player&6!'
    - ''
    - '&#ffdb60Будь ласка, введіть свій пароль для входу на сервер.'
    - ''
    inputs:
      password: Пароль
    buttons:
      login: Увійти
      recover: Забув пароль
      cancel: Вихід
  register:
    title: '&#ffdb60Створення пароля'
    body:
    - '&6Вітаю, &f@player&6!'
    - ''
    - '&#ffdb60Ви повині &bстворити пароль &#ffdb60щоб зайти на сервер.'
    - ''
    - '&#ffdb60Будь ласка, заповніть поля нижче, щоб продовжити.'
    - ''
    inputs:
      password1: Пароль
      password2: Підтвердження
    buttons:
      register: Створити акаунт
      cancel: Вихід

title:
  before-login:
    title: '&a&lВітаємо!'
    subtitle: '&7Напишіть: /login <ваш пароль>'
    delays:
      fadeIn: 6
      stay: 9999
      fadeOut: 6
  before-register:
    title: '&a&lВітаємо!'
    subtitle: '&7Напишіть: /register <ваш пароль> <підтвердження пароля>'
    delays:
      fadeIn: 6
      stay: 9999
      fadeOut: 6
  after-login:
    title: ''
    subtitle: '&aВи були успішно авторизовані!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  after-register:
    title: ''
    subtitle: '&aВи були успішно зареєстровані!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  incorrect-password:
    title: ''
    subtitle: '&cНевірний пароль!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  already-login:
    title: ''
    subtitle: '&fВи &cвже &fавторизовані!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  already-registered:
    title: ''
    subtitle: '&fВи &cвже &fзареєстровані!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  passwords-dont-match:
    title: ''
    subtitle: '&fПаролі &cне &fзбігаються!'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  session-login:
    title: ''
    subtitle: '&eВаш сеанс входу продовжено.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  premium-login:
    title: ''
    subtitle: '&eВи успішно авторизувались за допомогою &aліцензії.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  bedrock-login:
    title: ''
    subtitle: '&eВи успішно авторизувались за допомогою &aBedrock.'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  security-warning:
    title: ''
    subtitle: '&fНове сповіщення, &cщодо безпеки &fбуло надіслано в чат'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
  unconfirmed-message:
    title: ''
    subtitle: '&c‼ &eУ чаті є не підтверджене повідомлення'
    delays:
      fadeIn: 6
      stay: 60
      fadeOut: 6
